//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;

namespace WmsApi.Tracker
{
    public partial interface IParkingLotApi
    {
        [Post("/tracker/ParkingLot/CarPreInPush")]
        Task CarPreInPush();

        [Post("/tracker/ParkingLot/CarPreOutPush")]
        Task CarPreOutPush();

        [Post("/tracker/ParkingLot/CarOutConfirmPush")]
        Task CarOutConfirmPush();

        [Post("/tracker/ParkingLot/GateControl")]
        Task<OperationResult> GateControl([Body] GateControlParas para);

        [Post("/tracker/ParkingLot/GateOpenOrClose")]
        Task<OperationResult> GateOpenOrClose(string gateId = null, int? type = null);

        [Post("/tracker/ParkingLot/GatePlcOpenOrClose")]
        Task<OperationResult> GatePlcOpenOrClose(string gateId = null, int? type = null);

        [Post("/tracker/ParkingLot/CameraAlarmPush")]
        Task CameraAlarmPush();
    }
}