//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrTodoListApi
    {
        [Post("/tracker/TTrTodoList/Create")]
        Task<OperationResult> Create([Body] TTrTodoListCreateModel createModel);

        [Put("/tracker/TTrTodoList/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrTodoListUpdateModel updateModel);

        [Delete("/tracker/TTrTodoList/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrTodoList/Get/{id}")]
        Task<TTrTodoListReadModel> Get(string id);

        [Get("/tracker/TTrTodoList/GetPage")]
        Task<PageResult<TTrTodoListReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrTodoList/GetPageByString")]
        Task<PageResult<TTrTodoListReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrTodoList/GetListByString")]
        Task<PageResult<TTrTodoListReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrTodoList/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrTodoList/GetList")]
        Task<PageResult<TTrTodoListReadModel>> GetList();
    }
}