//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrEntryApi
    {
        [Get("/tracker/TTrEntry/GetGateEntry")]
        Task<PageResult<TTrEntryReadModel>> GetGateEntry();

        [Post("/tracker/TTrEntry/Create")]
        Task<OperationResult> Create([Body] TTrEntryCreateModel createModel);

        [Put("/tracker/TTrEntry/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrEntryUpdateModel updateModel);

        [Delete("/tracker/TTrEntry/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrEntry/Get/{id}")]
        Task<TTrEntryReadModel> Get(string id);

        [Get("/tracker/TTrEntry/GetPage")]
        Task<PageResult<TTrEntryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrEntry/GetPageByString")]
        Task<PageResult<TTrEntryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrEntry/GetListByString")]
        Task<PageResult<TTrEntryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrEntry/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrEntry/GetList")]
        Task<PageResult<TTrEntryReadModel>> GetList();
    }
}