//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrUserApi
    {
        [Post("/tracker/TTrUser/Create")]
        Task<OperationResult> Create([Body] TTrUserCreateModel createModel);

        [Put("/tracker/TTrUser/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrUserUpdateModel updateModel);

        [Delete("/tracker/TTrUser/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrUser/Get/{id}")]
        Task<TTrUserReadModel> Get(string id);

        [Get("/tracker/TTrUser/GetPage")]
        Task<PageResult<TTrUserReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrUser/GetPageByString")]
        Task<PageResult<TTrUserReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrUser/GetListByString")]
        Task<PageResult<TTrUserReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrUser/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrUser/GetList")]
        Task<PageResult<TTrUserReadModel>> GetList();
    }
}