//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrNetworkApi
    {
        [Get("/tracker/TTrNetwork/GetQueryList")]
        Task<PageResult<TTrNetworkReadModel>> GetQueryList(int[] isConnected = null, int[] isEnable = null);

        [Get("/tracker/TTrNetwork/UpdateState")]
        Task UpdateState();

        [Post("/tracker/TTrNetwork/RebootMoxa")]
        Task<bool> RebootMoxa(string name = null, string ip = null);

        [Post("/tracker/TTrNetwork/RebootFlatScan")]
        Task<bool> RebootFlatScan(string ip = null);

        [Post("/tracker/TTrNetwork/Create")]
        Task<OperationResult> Create([Body] TTrNetworkCreateModel createModel);

        [Put("/tracker/TTrNetwork/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrNetworkUpdateModel updateModel);

        [Delete("/tracker/TTrNetwork/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrNetwork/Get/{id}")]
        Task<TTrNetworkReadModel> Get(string id);

        [Get("/tracker/TTrNetwork/GetPage")]
        Task<PageResult<TTrNetworkReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrNetwork/GetPageByString")]
        Task<PageResult<TTrNetworkReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrNetwork/GetListByString")]
        Task<PageResult<TTrNetworkReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrNetwork/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrNetwork/GetList")]
        Task<PageResult<TTrNetworkReadModel>> GetList();
    }
}