//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrMessageSendApi
    {
        /// <summary>
        /// 批量启用/禁用=========重新发送
        /// </summary>
        /// <returns></returns>
        [Post("/tracker/TTrMessageSend/UpdateIsabled")]
        Task<OperationResult> UpdateIsabled([Query] string[] ids = null, int? isEnable = null);

        [Post("/tracker/TTrMessageSend/Create")]
        Task<OperationResult> Create([Body] TTrMessageSendCreateModel createModel);

        [Put("/tracker/TTrMessageSend/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrMessageSendUpdateModel updateModel);

        [Delete("/tracker/TTrMessageSend/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrMessageSend/Get/{id}")]
        Task<TTrMessageSendReadModel> Get(string id);

        [Get("/tracker/TTrMessageSend/GetPage")]
        Task<PageResult<TTrMessageSendReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrMessageSend/GetPageByString")]
        Task<PageResult<TTrMessageSendReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrMessageSend/GetListByString")]
        Task<PageResult<TTrMessageSendReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrMessageSend/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrMessageSend/GetList")]
        Task<PageResult<TTrMessageSendReadModel>> GetList();
    }
}