//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrCplApi
    {
        [Post("/tracker/TTrCpl/Create")]
        Task<OperationResult> Create([Body] TTrCplCreateModel createModel);

        [Put("/tracker/TTrCpl/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrCplUpdateModel updateModel);

        [Delete("/tracker/TTrCpl/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrCpl/Get/{id}")]
        Task<TTrCplReadModel> Get(string id);

        [Get("/tracker/TTrCpl/GetPage")]
        Task<PageResult<TTrCplReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrCpl/GetPageByString")]
        Task<PageResult<TTrCplReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrCpl/GetListByString")]
        Task<PageResult<TTrCplReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrCpl/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrCpl/GetList")]
        Task<PageResult<TTrCplReadModel>> GetList();
    }
}