//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrTruckQueueApi
    {
        [Post("/tracker/TTrTruckQueue/Create")]
        Task<OperationResult> Create([Body] TTrTruckQueueCreateModel createModel);

        [Put("/tracker/TTrTruckQueue/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrTruckQueueUpdateModel updateModel);

        [Delete("/tracker/TTrTruckQueue/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrTruckQueue/Get/{id}")]
        Task<TTrTruckQueueReadModel> Get(string id);

        [Get("/tracker/TTrTruckQueue/GetPage")]
        Task<PageResult<TTrTruckQueueReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrTruckQueue/GetPageByString")]
        Task<PageResult<TTrTruckQueueReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrTruckQueue/GetListByString")]
        Task<PageResult<TTrTruckQueueReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrTruckQueue/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrTruckQueue/GetList")]
        Task<PageResult<TTrTruckQueueReadModel>> GetList();
    }
}