//<auto-generated />

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrLocationMaterialApi
    {
        [Get("/tracker/TTrLocationMaterial/GetLmMappingOfBay")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetLmMappingOfBay(string bayId = null);

        [Get("/tracker/TTrLocationMaterial/GetLmMappingOfBayWPF")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetLmMappingOfBayWPF(string bayId = null);

        [Post("/tracker/TTrLocationMaterial/ReqMesMatInfo")]
        Task<OperationResult> ReqMesMatInfo(string materialNo = null);

        [Put("/tracker/TTrLocationMaterial/UpdateMaterialLock")]
        Task<OperationResult> UpdateMaterialLock(string id = null, string materialNo = null, int? lockMark = null, string lockReason = null);

        [Put("/tracker/TTrLocationMaterial/UpdateLocationLoad")]
        Task<OperationResult> UpdateLocationLoad(string locationName = null, int? isLoadEnable = null);

        [Post("/tracker/TTrLocationMaterial/CheckAreaLM")]
        Task<OperationResult> CheckAreaLM(string bayCode = null, decimal? minX = null, decimal? maxX = null);

        [Get("/tracker/TTrLocationMaterial/GetAllPageLMs")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllPageLMs();

        [Put("/tracker/TTrLocationMaterial/UpdateMaterialEdit")]
        Task<OperationResult> UpdateMaterialEdit(string id = null, string materialNo = null, int? type = null, int? isNot = null);

        [Put("/tracker/TTrLocationMaterial/UpdateMaterialState")]
        Task<TTrLocationMaterialReadModel> UpdateMaterialState(string locationId = null, string coilNo = null, PackTypes? packType = null, int? isHandlePack = null, string user = null);

        [Put("/tracker/TTrLocationMaterial/UpdateMaterial")]
        Task<OperationResult<TTrLocationMaterialReadModel>> UpdateMaterial(string locationId = null, string coilNo = null, int? defectType = null, string user = null);

        [Get("/tracker/TTrLocationMaterial/GetLocationMaterialByNo")]
        Task<TTrLocationMaterialReadModel> GetLocationMaterialByNo(string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/GetScanMaterial")]
        Task<TTrLocationMaterialReadModel> GetScanMaterial(string bayId = null, string materialNo = null);

        [Put("/tracker/TTrLocationMaterial/UpdateScanLocation")]
        Task<TTrLocationMaterialReadModel> UpdateScanLocation(string locationName = null, string plan = null, string coilNo = null, string user = null);

        [Get("/tracker/TTrLocationMaterial/GetLocationDetail")]
        Task<TTrLocationMaterialReadModel> GetLocationDetail(string ownerid = null);

        [Get("/tracker/TTrLocationMaterial/GetLocation")]
        Task<List<TTrLocationMaterialReadModel>> GetLocation();

        [Get("/tracker/TTrLocationMaterial/GetListOfStack")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetListOfStack(string stackId = null);

        [Get("/tracker/TTrLocationMaterial/GetStatOfAreas")]
        Task<List<AreaStatModel>> GetStatOfAreas(string bayId = null, string department = null);

        [Get("/tracker/TTrLocationMaterial/GetInventoryDetail")]
        Task<List<TTrLocationMaterialReadModel>> GetInventoryDetail(string planNo = null);

        [Get("/tracker/TTrLocationMaterial/GetAllColumns")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllColumns(string bayId = null, string areaCode = null, int rowNo = 0);

        [Get("/tracker/TTrLocationMaterial/GetAllRows")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllRows(string bayId = null, string areaCode = null, int? rowNo = null, int? storageType = null);

        [Get("/tracker/TTrLocationMaterial/GetChainQuery")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetChainQuery(int? current = null, int? pageSize = null, string key = null, string areaId = null);

        [Post("/tracker/TTrLocationMaterial/DeleteChainCoil")]
        Task<int> DeleteChainCoil(string bayCode = null, string areaCode = null, int? colNo = null, string materialNo = null);

        [Post("/tracker/TTrLocationMaterial/AddChainCoil")]
        Task<int> AddChainCoil(string bayCode = null, string areaCode = null, int? colNo = null, string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/IsExist")]
        Task<OperationResult> IsExist(string material = null, string newLocation = null);

        [Post("/tracker/TTrLocationMaterial/AddHoldChainCoil")]
        Task<OperationResult> AddHoldChainCoil(string locationId = null, string materialNo = null, string userName = null);

        [Post("/tracker/TTrLocationMaterial/DeleteHoldChainCoil")]
        Task<OperationResult> DeleteHoldChainCoil(string locationId = null, string userName = null);

        [Get("/tracker/TTrLocationMaterial/GetPageQuery")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetPageQuery(int? current = null, int? pageSize = null, int[] type = null, string[] bayId = null, string[] areaId = null, string[] stackId = null, int[] storageType = null, string materialNo = null, int[] isEnable = null);

        [Get("/tracker/TTrLocationMaterial/GetChainList")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetChainList(string key = null);

        [Get("/tracker/TTrLocationMaterial/GetAllMaterials")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllMaterials(string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/GetHoldAllMaterials")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetHoldAllMaterials(string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/GetAllLocation")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllLocation(string locationName = null);

        [Get("/tracker/TTrLocationMaterial/GetLocationName")]
        Task<TTrLocationMaterialReadModel> GetLocationName(string locationName = null);

        [Post("/tracker/TTrLocationMaterial/SendMaterialInfo")]
        Task<ItemResult<TTrLocationMaterialReadModel>> SendMaterialInfo(string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/GetAllAreaRows")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllAreaRows(string bayId = null, int? storeageType = null);

        [Get("/tracker/TTrLocationMaterial/GetAllTrolleybusCoils")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllTrolleybusCoils(string bayName = null, int? storageType = null);

        [Get("/tracker/TTrLocationMaterial/GetAllCrossCarCoils")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllCrossCarCoils(string bayName = null, int? storageType = null);

        [Get("/tracker/TTrLocationMaterial/GetAllTruckTransferCoils")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetAllTruckTransferCoils(string houseId = null);

        [Put("/tracker/TTrLocationMaterial/UpdateTaskState")]
        Task<int> UpdateTaskState(string bayId = null, string materialNo = null);

        [Get("/tracker/TTrLocationMaterial/GetLocMatList")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetLocMatList(string bayId = null);

        [Get("/tracker/TTrLocationMaterial/GetBayPercent")]
        Task<PageResult<LocationPercent>> GetBayPercent(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrLocationMaterial/GetStackPercent")]
        Task<PageResult<LocationPercent>> GetStackPercent(int? current = null, int? pageSize = null, string[] id = null);

        [Get("/tracker/TTrLocationMaterial/UpdateStackIsEnable")]
        Task<OperationResult> UpdateStackIsEnable();

        [Get("/tracker/TTrLocationMaterial/CreateLDMatReportExcel")]
        Task CreateLDMatReportExcel();

        [Get("/tracker/TTrLocationMaterial/CreateLDOrderReportExcel")]
        Task CreateLDOrderReportExcel();

        [Get("/tracker/TTrLocationMaterial/GetListOfLocationRange")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetListOfLocationRange(string areaId = null, string stackId = null, string stackId2 = null, string colNo = null, string colNo2 = null, int? type = null, string[] locationNames = null);

        [Get("/tracker/TTrLocationMaterial/GetListOfLocationRangeOrder")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetListOfLocationRangeOrder(string areaId = null, string stackId = null, string stackId2 = null, string colNo = null, string colNo2 = null, int? type = null, string loadLocationName = null);

        [Get("/tracker/TTrLocationMaterial/GetLocationType2")]
        Task<bool> GetLocationType2(string locationName = null);

        [Get("/tracker/TTrLocationMaterial/GetEndLocationYesBool")]
        Task<bool> GetEndLocationYesBool(string startlocationName = null, string endLocationName = null);

        [Get("/tracker/TTrLocationMaterial/GetStartFirstColNoSecondBool")]
        Task<bool> GetStartFirstColNoSecondBool(string locationName = null);

        [Get("/tracker/TTrLocationMaterial/GetEndSecondColNoFirstBool")]
        Task<bool> GetEndSecondColNoFirstBool(string locationName = null);

        [Get("/tracker/TTrLocationMaterial/GetLocationTypes")]
        Task<List<LocationStartEndRead>> GetLocationTypes(string bayId = null, string areaId = null, string startStackId = null, string endStackId = null, string startColNoId = null, string endColNoId = null, int? planCount = null);

        [Get("/tracker/TTrLocationMaterial/GetVcomparePageQuery")]
        Task<PageResult<VCompareNameNoReadModel>> GetVcomparePageQuery(int? current = null, int? pageSize = null, string[] bayIdWms = null, string type = null, string locationNameWms = null, string locationNameMes = null, string matNoWms = null, string matNoMes = null, string[] stockNoWms = null, string[] stockNoMes = null);

        [Post("/tracker/TTrLocationMaterial/Create")]
        Task<OperationResult> Create([Body] TTrLocationMaterialCreateModel createModel);

        [Put("/tracker/TTrLocationMaterial/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrLocationMaterialUpdateModel updateModel);

        [Delete("/tracker/TTrLocationMaterial/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrLocationMaterial/Get/{id}")]
        Task<TTrLocationMaterialReadModel> Get(string id);

        [Get("/tracker/TTrLocationMaterial/GetPage")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrLocationMaterial/GetPageByString")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrLocationMaterial/GetListByString")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrLocationMaterial/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrLocationMaterial/GetList")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetList();
    }
}