//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrCrossTrainApi
    {
        /// <summary>
        /// 各课过跨车
        /// </summary>
        /// <returns></returns>
        [Get("/tracker/TTrCrossTrain/GetCrossCar")]
        Task<TTrCrossTrainReadModel> GetCrossCar(string bayCode = null);

        /// <summary>
        /// 电瓶车信息
        /// </summary>
        /// <returns></returns>
        [Get("/tracker/TTrCrossTrain/GetElectronicVehicle")]
        Task<TTrCrossTrainReadModel> GetElectronicVehicle(string name = null);

        /// <summary>
        /// 更改过跨车锁定状态
        /// </summary>
        /// <returns></returns>
        [Post("/tracker/TTrCrossTrain/UpdateIsLock")]
        Task<OperationResult> UpdateIsLock(string id = null, int? islock = null);

        /// <summary>
        /// 过跨车作业类型更改
        /// </summary>
        /// <returns></returns>
        [Put("/tracker/TTrCrossTrain/UpdateCrossTrainTaskType")]
        Task<OperationResult> UpdateCrossTrainTaskType(string name = null, int? type = null, string fromBay = null, string destBay = null);

        [Post("/tracker/TTrCrossTrain/Create")]
        Task<OperationResult> Create([Body] TTrCrossTrainCreateModel createModel);

        [Put("/tracker/TTrCrossTrain/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrCrossTrainUpdateModel updateModel);

        [Delete("/tracker/TTrCrossTrain/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrCrossTrain/Get/{id}")]
        Task<TTrCrossTrainReadModel> Get(string id);

        [Get("/tracker/TTrCrossTrain/GetPage")]
        Task<PageResult<TTrCrossTrainReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrCrossTrain/GetPageByString")]
        Task<PageResult<TTrCrossTrainReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrCrossTrain/GetListByString")]
        Task<PageResult<TTrCrossTrainReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrCrossTrain/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrCrossTrain/GetList")]
        Task<PageResult<TTrCrossTrainReadModel>> GetList();
    }
}