//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrFenceAreaApi
    {
        [Post("/tracker/TTrFenceArea/Create")]
        Task<OperationResult> Create([Body] TTrFenceAreaCreateModel createModel);

        [Put("/tracker/TTrFenceArea/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrFenceAreaUpdateModel updateModel);

        [Delete("/tracker/TTrFenceArea/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrFenceArea/Get/{id}")]
        Task<TTrFenceAreaReadModel> Get(string id);

        [Get("/tracker/TTrFenceArea/GetPage")]
        Task<PageResult<TTrFenceAreaReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrFenceArea/GetPageByString")]
        Task<PageResult<TTrFenceAreaReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrFenceArea/GetListByString")]
        Task<PageResult<TTrFenceAreaReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrFenceArea/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrFenceArea/GetList")]
        Task<PageResult<TTrFenceAreaReadModel>> GetList();
    }
}