//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrLocationMaterialEventApi
    {
        [Post("/tracker/TTrLocationMaterialEvent/Create")]
        Task<OperationResult> Create([Body] TTrLocationMaterialEventCreateModel createModel);

        [Put("/tracker/TTrLocationMaterialEvent/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrLocationMaterialEventUpdateModel updateModel);

        [Delete("/tracker/TTrLocationMaterialEvent/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrLocationMaterialEvent/Get/{id}")]
        Task<TTrLocationMaterialEventReadModel> Get(string id);

        [Get("/tracker/TTrLocationMaterialEvent/GetPage")]
        Task<PageResult<TTrLocationMaterialEventReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrLocationMaterialEvent/GetPageByString")]
        Task<PageResult<TTrLocationMaterialEventReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrLocationMaterialEvent/GetListByString")]
        Task<PageResult<TTrLocationMaterialEventReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrLocationMaterialEvent/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrLocationMaterialEvent/GetList")]
        Task<PageResult<TTrLocationMaterialEventReadModel>> GetList();
    }
}