//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrMessageReceivedApi
    {
        [Post("/tracker/TTrMessageReceived/Create")]
        Task<OperationResult> Create([Body] TTrMessageReceivedCreateModel createModel);

        [Put("/tracker/TTrMessageReceived/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrMessageReceivedUpdateModel updateModel);

        [Delete("/tracker/TTrMessageReceived/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrMessageReceived/Get/{id}")]
        Task<TTrMessageReceivedReadModel> Get(string id);

        [Get("/tracker/TTrMessageReceived/GetPage")]
        Task<PageResult<TTrMessageReceivedReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrMessageReceived/GetPageByString")]
        Task<PageResult<TTrMessageReceivedReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrMessageReceived/GetListByString")]
        Task<PageResult<TTrMessageReceivedReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrMessageReceived/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrMessageReceived/GetList")]
        Task<PageResult<TTrMessageReceivedReadModel>> GetList();
    }
}