//<auto-generated />

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public partial interface ITTrTruckApi
    {
        [Get("/tracker/TTrTruck/GetAllTrucks")]
        Task<List<TTrTruckReadModel>> GetAllTrucks(string bayId = null);

        [Get("/tracker/TTrTruck/GetAllTruckLines")]
        Task<List<TTrTruckReadModel>> GetAllTruckLines(string bayName = null, int? dispatchState = null);

        [Get("/tracker/TTrTruck/TruckLoadConfirm")]
        Task<ValueTuple<bool, string>> TruckLoadConfirm(string houseId = null, string truckName = null);

        [Get("/tracker/TTrTruck/TruckPickConfirm")]
        Task<ValueTuple<bool, string>> TruckPickConfirm(string houseId = null, string truckName = null);

        [Get("/tracker/TTrTruck/TruckLeaveConfirm")]
        Task<ValueTuple<bool, string>> TruckLeaveConfirm(string houseId = null, string houseName = null, string truckName = null);

        [Get("/tracker/TTrTruck/TruckArriveStation")]
        Task<string> TruckArriveStation(string houseId = null, string truckName = null);

        [Get("/tracker/TTrTruck/TruckEntryStation")]
        Task<string> TruckEntryStation(string houseId = null, string truckId = null, int? stationNo = null);

        [Post("/tracker/TTrTruck/Create")]
        Task<OperationResult> Create([Body] TTrTruckCreateModel createModel);

        [Put("/tracker/TTrTruck/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrTruckUpdateModel updateModel);

        [Delete("/tracker/TTrTruck/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/tracker/TTrTruck/Get/{id}")]
        Task<TTrTruckReadModel> Get(string id);

        [Get("/tracker/TTrTruck/GetPage")]
        Task<PageResult<TTrTruckReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrTruck/GetPageByString")]
        Task<PageResult<TTrTruckReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrTruck/GetListByString")]
        Task<PageResult<TTrTruckReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrTruck/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrTruck/GetList")]
        Task<PageResult<TTrTruckReadModel>> GetList();
    }
}