//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrFenceDoorApi
    {
        /// <summary>
        /// 手持机扫码请求开门
        /// </summary>
        /// <returns></returns>
        [Put("/tracker/TTrFenceDoor/ScanOpenDoor")]
        Task<OperationResult> ScanOpenDoor(string fenceDoorCode = null, string userName = null);

        [Post("/tracker/TTrFenceDoor/Create")]
        Task<OperationResult> Create([Body] TTrFenceDoorCreateModel createModel);

        [Put("/tracker/TTrFenceDoor/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrFenceDoorUpdateModel updateModel);

        [Delete("/tracker/TTrFenceDoor/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrFenceDoor/Get/{id}")]
        Task<TTrFenceDoorReadModel> Get(string id);

        [Get("/tracker/TTrFenceDoor/GetPage")]
        Task<PageResult<TTrFenceDoorReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrFenceDoor/GetPageByString")]
        Task<PageResult<TTrFenceDoorReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrFenceDoor/GetListByString")]
        Task<PageResult<TTrFenceDoorReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrFenceDoor/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrFenceDoor/GetList")]
        Task<PageResult<TTrFenceDoorReadModel>> GetList();
    }
}