//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Tracker
{
    public interface ITTrTrainApi
    {
        [Post("/tracker/TTrTrain/Create")]
        Task<OperationResult> Create([Body] TTrTrainCreateModel createModel);

        [Put("/tracker/TTrTrain/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TTrTrainUpdateModel updateModel);

        [Delete("/tracker/TTrTrain/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/tracker/TTrTrain/Get/{id}")]
        Task<TTrTrainReadModel> Get(string id);

        [Get("/tracker/TTrTrain/GetPage")]
        Task<PageResult<TTrTrainReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/tracker/TTrTrain/GetPageByString")]
        Task<PageResult<TTrTrainReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/tracker/TTrTrain/GetListByString")]
        Task<PageResult<TTrTrainReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/tracker/TTrTrain/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/tracker/TTrTrain/GetList")]
        Task<PageResult<TTrTrainReadModel>> GetList();
    }
}