//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Auth
{
    public interface ILoginApi
    {
        [Post("/auth/Login/Login")]
        Task<LoginResultModel> Login(string userName = null, string password = null);

        [Post("/auth/Login/Create")]
        Task<OperationResult> Create([Body] TUmUserCreateModel createModel);

        [Put("/auth/Login/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmUserUpdateModel updateModel);

        [Delete("/auth/Login/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/auth/Login/Get/{id}")]
        Task<TUmUserReadModel> Get(string id);

        [Get("/auth/Login/GetPage")]
        Task<PageResult<TUmUserReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/auth/Login/GetPageByString")]
        Task<PageResult<TUmUserReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/auth/Login/GetListByString")]
        Task<PageResult<TUmUserReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/auth/Login/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/auth/Login/GetList")]
        Task<PageResult<TUmUserReadModel>> GetList();
    }
}