//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.ApiReport
{
    public interface ITRcBayApi
    {
        [Post("/report/TRcBay/Create")]
        Task<OperationResult> Create([Body] TRcBayCreateModel createModel);

        [Put("/report/TRcBay/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcBayUpdateModel updateModel);

        [Delete("/report/TRcBay/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcBay/Get/{id}")]
        Task<TRcBayReadModel> Get(string id);

        [Get("/report/TRcBay/GetPage")]
        Task<PageResult<TRcBayReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcBay/GetPageByString")]
        Task<PageResult<TRcBayReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcBay/GetListByString")]
        Task<PageResult<TRcBayReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcBay/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcBay/GetList")]
        Task<PageResult<TRcBayReadModel>> GetList();
    }
}