//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.ApiReport
{
    public partial interface ITRcTruckQueueApi
    {
        [Get("/report/TRcTruckQueue/GetPageByStringH")]
        Task<PageResult<TRcTruckBayQueueWithCountDto>> GetPageByStringH(int? current = null, int? pageSize = null, string where = null, string[] time = null, string orders = null);

        [Post("/report/TRcTruckQueue/Create")]
        Task<OperationResult> Create([Body] TRcTruckBayQueueCreateModel createModel);

        [Put("/report/TRcTruckQueue/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTruckBayQueueUpdateModel updateModel);

        [Delete("/report/TRcTruckQueue/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/report/TRcTruckQueue/Get/{id}")]
        Task<TRcTruckBayQueueReadModel> Get(string id);

        [Get("/report/TRcTruckQueue/GetPage")]
        Task<PageResult<TRcTruckBayQueueReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTruckQueue/GetPageByString")]
        Task<PageResult<TRcTruckBayQueueReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTruckQueue/GetListByString")]
        Task<PageResult<TRcTruckBayQueueReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTruckQueue/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTruckQueue/GetList")]
        Task<PageResult<TRcTruckBayQueueReadModel>> GetList();
    }
}