//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public interface ITEqCraneApi
    {
        [Get("/equip/TEqCrane/GetListOfBay")]
        Task<PageResult<TEqCraneReadModel>> GetListOfBay(string bayId = null);

        [Post("/equip/TEqCrane/Create")]
        Task<OperationResult> Create([Body] TEqCraneCreateModel createModel);

        [Put("/equip/TEqCrane/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqCraneUpdateModel updateModel);

        /// <summary>
        /// 行车前往待机位
        /// </summary>
        /// <returns></returns>
        [Post("/equip/TEqCrane/SendCraneCmd")]
        Task<OperationResult> SendCraneCmd(string craneId = null, int? cmd = null);

        [Delete("/equip/TEqCrane/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/equip/TEqCrane/Get/{id}")]
        Task<TEqCraneReadModel> Get(string id);

        [Get("/equip/TEqCrane/GetPage")]
        Task<PageResult<TEqCraneReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqCrane/GetPageByString")]
        Task<PageResult<TEqCraneReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqCrane/GetListByString")]
        Task<PageResult<TEqCraneReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqCrane/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqCrane/GetList")]
        Task<PageResult<TEqCraneReadModel>> GetList();
    }
}