//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqCraneWeightApi
    {
        [Post("/equip/TEqCraneWeight/Create")]
        Task<OperationResult> Create([Body] TEqCraneWeightCreateModel createModel);

        [Put("/equip/TEqCraneWeight/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqCraneWeightUpdateModel updateModel);

        [Delete("/equip/TEqCraneWeight/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqCraneWeight/Get/{id}")]
        Task<TEqCraneWeightReadModel> Get(string id);

        [Get("/equip/TEqCraneWeight/GetPage")]
        Task<PageResult<TEqCraneWeightReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqCraneWeight/GetPageByString")]
        Task<PageResult<TEqCraneWeightReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqCraneWeight/GetListByString")]
        Task<PageResult<TEqCraneWeightReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqCraneWeight/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqCraneWeight/GetList")]
        Task<PageResult<TEqCraneWeightReadModel>> GetList();
    }
}