//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public interface ITEqCoilCarApi
    {
        [Post("/equip/TEqCoilCar/Create")]
        Task<OperationResult> Create([Body] TEqCoilCarCreateModel createModel);

        [Put("/equip/TEqCoilCar/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqCoilCarUpdateModel updateModel);

        [Delete("/equip/TEqCoilCar/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/equip/TEqCoilCar/Get/{id}")]
        Task<TEqCoilCarReadModel> Get(string id);

        [Get("/equip/TEqCoilCar/GetPage")]
        Task<PageResult<TEqCoilCarReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqCoilCar/GetPageByString")]
        Task<PageResult<TEqCoilCarReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqCoilCar/GetListByString")]
        Task<PageResult<TEqCoilCarReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqCoilCar/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqCoilCar/GetList")]
        Task<PageResult<TEqCoilCarReadModel>> GetList();
    }
}