//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public interface ITEqFenceDoorApi
    {
        [Post("/equip/TEqFenceDoor/Create")]
        Task<OperationResult> Create([Body] TEqFenceDoorCreateModel createModel);

        [Put("/equip/TEqFenceDoor/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqFenceDoorUpdateModel updateModel);

        [Delete("/equip/TEqFenceDoor/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/equip/TEqFenceDoor/Get/{id}")]
        Task<TEqFenceDoorReadModel> Get(string id);

        [Get("/equip/TEqFenceDoor/GetPage")]
        Task<PageResult<TEqFenceDoorReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqFenceDoor/GetPageByString")]
        Task<PageResult<TEqFenceDoorReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqFenceDoor/GetListByString")]
        Task<PageResult<TEqFenceDoorReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqFenceDoor/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqFenceDoor/GetList")]
        Task<PageResult<TEqFenceDoorReadModel>> GetList();
    }
}