//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqTrainApi
    {
        [Post("/equip/TEqTrain/Create")]
        Task<OperationResult> Create([Body] TEqTrainCreateModel createModel);

        [Put("/equip/TEqTrain/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqTrainUpdateModel updateModel);

        [Delete("/equip/TEqTrain/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqTrain/Get/{id}")]
        Task<TEqTrainReadModel> Get(string id);

        [Get("/equip/TEqTrain/GetPage")]
        Task<PageResult<TEqTrainReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqTrain/GetPageByString")]
        Task<PageResult<TEqTrainReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqTrain/GetListByString")]
        Task<PageResult<TEqTrainReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqTrain/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqTrain/GetList")]
        Task<PageResult<TEqTrainReadModel>> GetList();
    }
}