//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqWalkingBeamApi
    {
        [Post("/equip/TEqWalkingBeam/Create")]
        Task<OperationResult> Create([Body] TEqWalkingBeamCreateModel createModel);

        [Put("/equip/TEqWalkingBeam/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqWalkingBeamUpdateModel updateModel);

        [Delete("/equip/TEqWalkingBeam/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqWalkingBeam/Get/{id}")]
        Task<TEqWalkingBeamReadModel> Get(string id);

        [Get("/equip/TEqWalkingBeam/GetPage")]
        Task<PageResult<TEqWalkingBeamReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqWalkingBeam/GetPageByString")]
        Task<PageResult<TEqWalkingBeamReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqWalkingBeam/GetListByString")]
        Task<PageResult<TEqWalkingBeamReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqWalkingBeam/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqWalkingBeam/GetList")]
        Task<PageResult<TEqWalkingBeamReadModel>> GetList();
    }
}