//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqGateParkingApi
    {
        [Post("/equip/TEqGateParking/Create")]
        Task<OperationResult> Create([Body] TEqGateParkingCreateModel createModel);

        [Put("/equip/TEqGateParking/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqGateParkingUpdateModel updateModel);

        [Delete("/equip/TEqGateParking/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqGateParking/Get/{id}")]
        Task<TEqGateParkingReadModel> Get(string id);

        [Get("/equip/TEqGateParking/GetPage")]
        Task<PageResult<TEqGateParkingReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqGateParking/GetPageByString")]
        Task<PageResult<TEqGateParkingReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqGateParking/GetListByString")]
        Task<PageResult<TEqGateParkingReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqGateParking/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqGateParking/GetList")]
        Task<PageResult<TEqGateParkingReadModel>> GetList();
    }
}