//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public interface ITEqCrossVehicleApi
    {
        /// <summary>
        /// 各课过跨车
        /// </summary>
        /// <returns></returns>
        [Get("/equip/TEqCrossVehicle/GetCrossCar")]
        Task<TEqCrossVehicleReadModel> GetCrossCar(string bayCode = null);

        /// <summary>
        /// 过跨车去向发送
        /// </summary>
        /// <returns></returns>
        [Post("/equip/TEqCrossVehicle/SendCrossTrainMove")]
        Task<OperationResult> SendCrossTrainMove(string name = null, string bayName = null, int? opCmd = null);

        /// <summary>
        /// 获取电瓶车
        /// </summary>
        /// <returns></returns>
        [Get("/equip/TEqCrossVehicle/GetElectronicVehicle")]
        Task<PageResult<TEqCrossVehicleReadModel>> GetElectronicVehicle();

        [Post("/equip/TEqCrossVehicle/Create")]
        Task<OperationResult> Create([Body] TEqCrossVehicleCreateModel createModel);

        [Put("/equip/TEqCrossVehicle/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqCrossVehicleUpdateModel updateModel);

        [Delete("/equip/TEqCrossVehicle/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/equip/TEqCrossVehicle/Get/{id}")]
        Task<TEqCrossVehicleReadModel> Get(string id);

        [Get("/equip/TEqCrossVehicle/GetPage")]
        Task<PageResult<TEqCrossVehicleReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqCrossVehicle/GetPageByString")]
        Task<PageResult<TEqCrossVehicleReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqCrossVehicle/GetListByString")]
        Task<PageResult<TEqCrossVehicleReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqCrossVehicle/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqCrossVehicle/GetList")]
        Task<PageResult<TEqCrossVehicleReadModel>> GetList();
    }
}