//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqFenceAreaApi
    {
        [Post("/equip/TEqFenceArea/Create")]
        Task<OperationResult> Create([Body] TEqFenceAreaCreateModel createModel);

        [Put("/equip/TEqFenceArea/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqFenceAreaUpdateModel updateModel);

        [Delete("/equip/TEqFenceArea/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqFenceArea/Get/{id}")]
        Task<TEqFenceAreaReadModel> Get(string id);

        [Get("/equip/TEqFenceArea/GetPage")]
        Task<PageResult<TEqFenceAreaReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqFenceArea/GetPageByString")]
        Task<PageResult<TEqFenceAreaReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqFenceArea/GetListByString")]
        Task<PageResult<TEqFenceAreaReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqFenceArea/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqFenceArea/GetList")]
        Task<PageResult<TEqFenceAreaReadModel>> GetList();
    }
}