//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqGateEntryApi
    {
        [Post("/equip/TEqGateEntry/Create")]
        Task<OperationResult> Create([Body] TEqGateEntryCreateModel createModel);

        [Put("/equip/TEqGateEntry/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqGateEntryUpdateModel updateModel);

        [Delete("/equip/TEqGateEntry/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqGateEntry/Get/{id}")]
        Task<TEqGateEntryReadModel> Get(string id);

        [Get("/equip/TEqGateEntry/GetPage")]
        Task<PageResult<TEqGateEntryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqGateEntry/GetPageByString")]
        Task<PageResult<TEqGateEntryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqGateEntry/GetListByString")]
        Task<PageResult<TEqGateEntryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqGateEntry/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqGateEntry/GetList")]
        Task<PageResult<TEqGateEntryReadModel>> GetList();
    }
}