//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Equip
{
    public partial interface ITEqTrainCarApi
    {
        [Post("/equip/TEqTrainCar/Create")]
        Task<OperationResult> Create([Body] TEqTrainCarCreateModel createModel);

        [Put("/equip/TEqTrainCar/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TEqTrainCarUpdateModel updateModel);

        [Delete("/equip/TEqTrainCar/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/equip/TEqTrainCar/Get/{id}")]
        Task<TEqTrainCarReadModel> Get(string id);

        [Get("/equip/TEqTrainCar/GetPage")]
        Task<PageResult<TEqTrainCarReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/equip/TEqTrainCar/GetPageByString")]
        Task<PageResult<TEqTrainCarReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/equip/TEqTrainCar/GetListByString")]
        Task<PageResult<TEqTrainCarReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/equip/TEqTrainCar/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/equip/TEqTrainCar/GetList")]
        Task<PageResult<TEqTrainCarReadModel>> GetList();
    }
}