//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhCraneTravelSpaceApi
    {
        [Put("/store/TWhCraneTravelSpace/UpdateTravelSpace")]
        Task<OperationResult<TWhCraneTravelSpaceReadModel>> UpdateTravelSpace(string bayId = null, string id = null, int? isEnable = null);

        [Get("/store/TWhCraneTravelSpace/GetAllAreaBayId")]
        Task<PageResult<TWhCraneTravelSpaceReadModel>> GetAllAreaBayId(string bayId = null);

        [Post("/store/TWhCraneTravelSpace/Create")]
        Task<OperationResult> Create([Body] TWhCraneTravelSpaceCreateModel createModel);

        [Put("/store/TWhCraneTravelSpace/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhCraneTravelSpaceUpdateModel updateModel);

        [Delete("/store/TWhCraneTravelSpace/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhCraneTravelSpace/Get/{id}")]
        Task<TWhCraneTravelSpaceReadModel> Get(string id);

        [Get("/store/TWhCraneTravelSpace/GetPage")]
        Task<PageResult<TWhCraneTravelSpaceReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhCraneTravelSpace/GetPageByString")]
        Task<PageResult<TWhCraneTravelSpaceReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhCraneTravelSpace/GetListByString")]
        Task<PageResult<TWhCraneTravelSpaceReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhCraneTravelSpace/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhCraneTravelSpace/GetList")]
        Task<PageResult<TWhCraneTravelSpaceReadModel>> GetList();
    }
}