//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public interface ITWhBayApi
    {
        /// <summary>
        /// 获取所有的跨列表
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/store/TWhBay/GetAllList")]
        Task<PageResult<TWhBayReadModel>> GetAllList();

        [Get("/store/TWhBay/GetAllBays")]
        Task<PageResult<TWhBayReadModel>> GetAllBays();

        [Get("/store/TWhBay/GetBayInfo")]
        Task<PageResult<TWhBayReadModel>> GetBayInfo([Body] List<int> bayNoList);

        [Post("/store/TWhBay/Create")]
        Task<OperationResult> Create([Body] TWhBayCreateModel createModel);

        [Put("/store/TWhBay/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhBayUpdateModel updateModel);

        [Delete("/store/TWhBay/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/store/TWhBay/Get/{id}")]
        Task<TWhBayReadModel> Get(string id);

        [Get("/store/TWhBay/GetPage")]
        Task<PageResult<TWhBayReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhBay/GetPageByString")]
        Task<PageResult<TWhBayReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhBay/GetListByString")]
        Task<PageResult<TWhBayReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhBay/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhBay/GetList")]
        Task<PageResult<TWhBayReadModel>> GetList();
    }
}