//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhTrainLocationApi
    {
        [Post("/store/TWhTrainLocation/Create")]
        Task<OperationResult> Create([Body] TWhTrainLocationCreateModel createModel);

        [Put("/store/TWhTrainLocation/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhTrainLocationUpdateModel updateModel);

        [Delete("/store/TWhTrainLocation/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhTrainLocation/Get/{id}")]
        Task<TWhTrainLocationReadModel> Get(string id);

        [Get("/store/TWhTrainLocation/GetPage")]
        Task<PageResult<TWhTrainLocationReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhTrainLocation/GetPageByString")]
        Task<PageResult<TWhTrainLocationReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhTrainLocation/GetListByString")]
        Task<PageResult<TWhTrainLocationReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhTrainLocation/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhTrainLocation/GetList")]
        Task<PageResult<TWhTrainLocationReadModel>> GetList();
    }
}