//<auto-generated />

using System;
using System.Threading.Tasks;
using Cds.Contracts;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhStackApi
    {
        [Get("/store/TWhStack/GetListOfArea")]
        Task<PageResult<TWhStackReadModel>> GetListOfArea(string areaId = null, StackTypes? stackType = null);

        [Get("/store/TWhStack/GetListOfAreaList")]
        Task<PageResult<TWhStackReadModel>> GetListOfAreaList(string[] areaIds = null);

        [Get("/store/TWhStack/GetListOfBay")]
        Task<PageResult<TWhStackReadModel>> GetListOfBay(string bayId = null, StackTypes? stackType = null);

        [Get("/store/TWhStack/GetPageQuery")]
        Task<PageResult<TWhStackReadModel>> GetPageQuery(int? current = null, int? pageSize = null, string[] bayId = null, string[] ownerId = null, int[] orientation = null, int[] type = null, int?[] isLockable = null, int[] loadOrder = null, int?[] isEnable = null);

        [Post("/store/TWhStack/Create")]
        Task<OperationResult> Create([Body] TWhStackCreateModel createModel);

        [Put("/store/TWhStack/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhStackUpdateModel updateModel);

        [Delete("/store/TWhStack/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhStack/Get/{id}")]
        Task<TWhStackReadModel> Get(string id);

        [Get("/store/TWhStack/GetPage")]
        Task<PageResult<TWhStackReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhStack/GetPageByString")]
        Task<PageResult<TWhStackReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhStack/GetListByString")]
        Task<PageResult<TWhStackReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhStack/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhStack/GetList")]
        Task<PageResult<TWhStackReadModel>> GetList();
    }
}