//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhAreaApi
    {
        [Post("/store/TWhArea/Create")]
        Task<OperationResult> Create([Body] TWhAreaCreateModel createModel);

        [Get("/store/TWhArea/GetListOfBay")]
        Task<PageResult<TWhAreaReadModel>> GetListOfBay(string bayId = null);

        [Post("/store/TWhArea/SendMesInfo")]
        Task<OperationResult> SendMesInfo(string ownerBussinessName = null, string bayArea = null, string user = null);

        [Get("/store/TWhArea/GetListOfBayList")]
        Task<PageResult<TWhAreaReadModel>> GetListOfBayList(string[] bayIds = null);

        [Get("/store/TWhArea/GetPageQuery")]
        Task<PageResult<TWhAreaReadModel>> GetPageQuery(int? current = null, int? pageSize = null, string[] ownerId = null, int[] isVirtual = null, int[] isEnable = null);

        [Put("/store/TWhArea/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhAreaUpdateModel updateModel);

        [Delete("/store/TWhArea/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhArea/Get/{id}")]
        Task<TWhAreaReadModel> Get(string id);

        [Get("/store/TWhArea/GetPage")]
        Task<PageResult<TWhAreaReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhArea/GetPageByString")]
        Task<PageResult<TWhAreaReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhArea/GetListByString")]
        Task<PageResult<TWhAreaReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhArea/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhArea/GetList")]
        Task<PageResult<TWhAreaReadModel>> GetList();
    }
}