//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public interface ITWhCranePassageApi
    {
        [Post("/store/TWhCranePassage/Create")]
        Task<OperationResult> Create([Body] TWhCranePassageCreateModel createModel);

        [Put("/store/TWhCranePassage/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhCranePassageUpdateModel updateModel);

        [Delete("/store/TWhCranePassage/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/store/TWhCranePassage/Get/{id}")]
        Task<TWhCranePassageReadModel> Get(string id);

        [Get("/store/TWhCranePassage/GetPage")]
        Task<PageResult<TWhCranePassageReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhCranePassage/GetPageByString")]
        Task<PageResult<TWhCranePassageReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhCranePassage/GetListByString")]
        Task<PageResult<TWhCranePassageReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhCranePassage/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhCranePassage/GetList")]
        Task<PageResult<TWhCranePassageReadModel>> GetList();
    }
}