//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhTruckPassageApi
    {
        [Post("/store/TWhTruckPassage/Create")]
        Task<OperationResult> Create([Body] TWhTruckPassageCreateModel createModel);

        [Put("/store/TWhTruckPassage/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhTruckPassageUpdateModel updateModel);

        [Delete("/store/TWhTruckPassage/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhTruckPassage/Get/{id}")]
        Task<TWhTruckPassageReadModel> Get(string id);

        [Get("/store/TWhTruckPassage/GetPage")]
        Task<PageResult<TWhTruckPassageReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhTruckPassage/GetPageByString")]
        Task<PageResult<TWhTruckPassageReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhTruckPassage/GetListByString")]
        Task<PageResult<TWhTruckPassageReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhTruckPassage/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhTruckPassage/GetList")]
        Task<PageResult<TWhTruckPassageReadModel>> GetList();
    }
}