//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public interface ITWhLocationApi
    {
        [Get("/store/TWhLocation/GetListQuery")]
        Task<PageResult<TWhLocationReadModel>> GetListQuery([Query] string[] bayId = null, [Query] string[] areaId = null, [Query] string[] ownerId = null);

        /// <summary>
        /// 库位信息筛选
        /// </summary>
        /// <returns></returns>
        [Get("/store/TWhLocation/GetPageQuery")]
        Task<PageResult<TWhLocationReadModel>> GetPageQuery(int? current = null, int? pageSize = null, [Query] string[] bayId = null, [Query] string[] areaId = null, [Query] string[] ownerId = null, [Query] int[] floorNo = null, [Query] int[] orientation = null, [Query] int[] isVirtual = null, [Query] int[] storageType = null, [Query] int[] loadType = null, [Query] int[] isEnable = null);

        /// <summary>
        /// 库位批量禁用
        /// </summary>
        /// <returns></returns>
        [Post("/store/TWhLocation/UpdateLocationDisabled")]
        Task<PageResult<TWhLocationReadModel>> UpdateLocationDisabled([Query] string[] ids = null, string remark = null);

        /// <summary>
        /// 库位批量启用
        /// </summary>
        /// <returns></returns>
        [Post("/store/TWhLocation/UpdateLocationIsEnable")]
        Task<PageResult<TWhLocationReadModel>> UpdateLocationIsEnable([Query] string[] ids = null, string remark = null);

        [Get("/store/TWhLocation/GetLocation")]
        Task<TWhLocationReadModel> GetLocation(string locationId = null);

        [Get("/store/TWhLocation/GetLocationByName")]
        Task<TWhLocationReadModel> GetLocationByName(string locationName = null);

        [Put("/store/TWhLocation/HoldUpdateLocation")]
        Task<OperationResult<TWhLocationReadModel>> HoldUpdateLocation(string locationId = null, decimal? pointX = null, decimal? pointY = null, int? isEnable = null);

        [Put("/store/TWhLocation/UpdateLocation")]
        Task<int> UpdateLocation([Body] TWhLocationReadModel location);

        [Post("/store/TWhLocation/BatchCreateLocations")]
        Task<bool> BatchCreateLocations([Body] BatchCreateLocationParam param);

        /// <summary>
        /// 批量更新鞍座行列坐标
        /// </summary>
        /// <param name="param"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Post("/store/TWhLocation/BatchUpdateLocationXY")]
        Task<bool> BatchUpdateLocationXY([Body] BatchAdjustXyParam param);

        /// <summary>
        /// 批量更改鞍座行间距
        /// </summary>
        /// <param name="param"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Post("/store/TWhLocation/BatchUpdateLocationSpacing")]
        Task<bool> BatchUpdateLocationSpacing([Body] BatchSpacingParam param);

        /// <summary>
        /// 创建库位
        /// </summary>
        /// <returns></returns>
        [Post("/store/TWhLocation/SendMesInfo")]
        Task<OperationResult> SendMesInfo([Body] TWhLocationCreateModel createModel);

        [Post("/store/TWhLocation/Create")]
        Task<OperationResult> Create([Body] TWhLocationCreateModel createModel);

        [Put("/store/TWhLocation/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhLocationUpdateModel updateModel);

        [Delete("/store/TWhLocation/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        /// <summary>
        /// 批量更新区域类型
        /// </summary>
        /// <returns></returns>
        [Post("/store/TWhLocation/UpdateLocationBuss")]
        Task<OperationResult> UpdateLocationBuss(string bayId = null, string areaId = null, string stackId = null, string buss = null);

        /// <summary>
        /// 批量更新库位类型
        /// </summary>
        /// <returns></returns>
        [Post("/store/TWhLocation/UpdateLocationStorageType")]
        Task<OperationResult> UpdateLocationStorageType(string bayId = null, string areaId = null, string stackId = null, int? storageType = null);

        /// <summary>
        /// 获取列号
        /// </summary>
        /// <param name="stackId"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/store/TWhLocation/GetListOfLocation")]
        Task<PageResult<TWhLocationReadModel>> GetListOfLocation(string stackId = null);

        [Post("/store/TWhLocation/UpdateLocationNameAndColNo")]
        Task<OperationResult> UpdateLocationNameAndColNo(string baycode = null, string areacode = null, int? addnum = null);

        [Get("/store/TWhLocation/Get/{id}")]
        Task<TWhLocationReadModel> Get(string id);

        [Get("/store/TWhLocation/GetPage")]
        Task<PageResult<TWhLocationReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhLocation/GetPageByString")]
        Task<PageResult<TWhLocationReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhLocation/GetListByString")]
        Task<PageResult<TWhLocationReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhLocation/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhLocation/GetList")]
        Task<PageResult<TWhLocationReadModel>> GetList();
    }
}