//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public interface ITWhTruckParkingPlaceApi
    {
        [Post("/store/TWhTruckParkingPlace/Create")]
        Task<OperationResult> Create([Body] TWhTruckParkingPlaceCreateModel createModel);

        [Put("/store/TWhTruckParkingPlace/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhTruckParkingPlaceUpdateModel updateModel);

        [Delete("/store/TWhTruckParkingPlace/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/store/TWhTruckParkingPlace/Get/{id}")]
        Task<TWhTruckParkingPlaceReadModel> Get(string id);

        [Get("/store/TWhTruckParkingPlace/GetPage")]
        Task<PageResult<TWhTruckParkingPlaceReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhTruckParkingPlace/GetPageByString")]
        Task<PageResult<TWhTruckParkingPlaceReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhTruckParkingPlace/GetListByString")]
        Task<PageResult<TWhTruckParkingPlaceReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhTruckParkingPlace/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhTruckParkingPlace/GetList")]
        Task<PageResult<TWhTruckParkingPlaceReadModel>> GetList();
    }
}