//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhWarehouseApi
    {
        [Post("/store/TWhWarehouse/Create")]
        Task<OperationResult> Create([Body] TWhWarehouseCreateModel createModel);

        [Put("/store/TWhWarehouse/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhWarehouseUpdateModel updateModel);

        [Delete("/store/TWhWarehouse/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhWarehouse/Get/{id}")]
        Task<TWhWarehouseReadModel> Get(string id);

        [Get("/store/TWhWarehouse/GetPage")]
        Task<PageResult<TWhWarehouseReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhWarehouse/GetPageByString")]
        Task<PageResult<TWhWarehouseReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhWarehouse/GetListByString")]
        Task<PageResult<TWhWarehouseReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhWarehouse/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhWarehouse/GetList")]
        Task<PageResult<TWhWarehouseReadModel>> GetList();
    }
}