//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public interface ITWhDestHouseApi
    {
        [Post("/store/TWhDestHouse/Create")]
        Task<OperationResult> Create([Body] TWhDestHouseCreateModel createModel);

        [Put("/store/TWhDestHouse/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhDestHouseUpdateModel updateModel);

        [Delete("/store/TWhDestHouse/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/store/TWhDestHouse/Get/{id}")]
        Task<TWhDestHouseReadModel> Get(string id);

        [Get("/store/TWhDestHouse/GetPage")]
        Task<PageResult<TWhDestHouseReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhDestHouse/GetPageByString")]
        Task<PageResult<TWhDestHouseReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhDestHouse/GetListByString")]
        Task<PageResult<TWhDestHouseReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhDestHouse/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhDestHouse/GetList")]
        Task<PageResult<TWhDestHouseReadModel>> GetList();
    }
}