//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Store
{
    public partial interface ITWhPlanTypeApi
    {
        [Post("/store/TWhPlanType/Create")]
        Task<OperationResult> Create([Body] TWhPlanTypeCreateModel createModel);

        [Put("/store/TWhPlanType/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TWhPlanTypeUpdateModel updateModel);

        [Delete("/store/TWhPlanType/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/store/TWhPlanType/Get/{id}")]
        Task<TWhPlanTypeReadModel> Get(string id);

        [Get("/store/TWhPlanType/GetPage")]
        Task<PageResult<TWhPlanTypeReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/store/TWhPlanType/GetPageByString")]
        Task<PageResult<TWhPlanTypeReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/store/TWhPlanType/GetListByString")]
        Task<PageResult<TWhPlanTypeReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/store/TWhPlanType/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/store/TWhPlanType/GetList")]
        Task<PageResult<TWhPlanTypeReadModel>> GetList();
    }
}