//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Cds.Contracts;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public partial interface IDashboardApi
    {
        [Get("/report/Dashboard/GetCraneInbound")]
        Task<PageResult<int>> GetCraneInbound(string bayId = null);

        [Get("/report/Dashboard/GetCraneOutbound")]
        Task<PageResult<int>> GetCraneOutbound(string bayId = null);

        [Get("/report/Dashboard/GetStackNum")]
        Task<PageResult<StackNumModel>> GetStackNum(string bayId = null, int? floor = null);

        [Get("/report/Dashboard/GetGroup")]
        Task<PageResult<List<int>>> GetGroup(string bayId = null);

        [Get("/report/Dashboard/GetCraneTask")]
        Task<PageResult<TPlBayReadModel>> GetCraneTask(string bayId = null);

        [Get("/report/Dashboard/GetDayTask")]
        Task<PageResult<double>> GetDayTask(string bayId = null);

        [Get("/report/Dashboard/GetMaterialWidth")]
        Task<PageResult<StackNumModel>> GetMaterialWidth(string bayId = null);

        [Get("/report/Dashboard/GetMaterialInTime")]
        Task<PageResult<StackNumModel>> GetMaterialInTime(string bayId = null);

        [Get("/report/Dashboard/GetSlabModel")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetSlabModel(string bayId = null);

        [Get("/report/Dashboard/GetSlabModelAz")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetSlabModelAz(string bayId = null);

        [Get("/report/Dashboard/GetCraneSpeed")]
        Task<PageResult<CraneSpeed>> GetCraneSpeed(string bayId = null);

        [Get("/report/Dashboard/GetBIList")]
        Task<PageResult<BLModel>> GetBIList(int? current = null, int? pageSize = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListNew")]
        Task<PageResult<BLModel>> GetBIListNew(int? current = null, int? pageSize = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListDetail")]
        Task<PageResult<TRcMaterialEventReadModel>> GetBIListDetail(int? current = null, int? pageSize = null, string bayId = null, string type = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListDetailCommon")]
        Task<PageResult<TRcMaterialEventReadModel>> GetBIListDetailCommon(string bayId = null, string type = null, string[] time = null);

        [Get("/report/Dashboard/GetClassListExcel")]
        Task GetClassListExcel(string house = null, string bayCode = null, string[] time = null);

        [Get("/report/Dashboard/GetProduceExcel")]
        Task GetProduceExcel();

        [Get("/report/Dashboard/GetCraneListExcel")]
        Task GetCraneListExcel(string bayCode = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListDetailExcel")]
        Task GetBIListDetailExcel(string bayId = null, string type = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListCommon")]
        Task<PageResult<BLModel>> GetBIListCommon(string baycode = null, string[] time = null);

        [Get("/report/Dashboard/CreateReportExcelHour")]
        Task CreateReportExcelHour(string baycode = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListCommonDay2")]
        Task<PageResult<BLModel>> GetBIListCommonDay2(string baycode = null, string[] time = null);

        [Get("/report/Dashboard/GetBIListCommonDay")]
        Task<PageResult<BLModel>> GetBIListCommonDay(string baycode = null, string[] time = null);

        [Get("/report/Dashboard/CreateReportExcelDay")]
        Task CreateReportExcelDay(string baycode = null, string[] time = null);

        [Get("/report/Dashboard/GetMaterialVirtual")]
        Task<PageResult<MaterialVirtualModel>> GetMaterialVirtual(int? current = null, int? pageSize = null);

        [Get("/report/Dashboard/GetMaterialVirtualDetail")]
        Task<PageResult<TTrLocationMaterialReadModel>> GetMaterialVirtualDetail(string bayId = null);

        [Get("/report/Dashboard/GetMaterialHandBag")]
        Task<PageResult<VPlMaterialReadModel>> GetMaterialHandBag(int? current = null, int? pageSize = null, string[] bayCode = null);

        [Get("/report/Dashboard/GetMaterialHandBagCommon")]
        Task<PageResult<VPlMaterialReadModel>> GetMaterialHandBagCommon(string[] bayCode = null);

        [Get("/report/Dashboard/GetMaterialHandBagExcel")]
        Task GetMaterialHandBagExcel(string[] bayCode = null);

        [Get("/report/Dashboard/GetWebsocket")]
        Task<PageResult<BLModel>> GetWebsocket(string message = null);

        [Get("/report/Dashboard/PrePickConfirm")]
        Task<PageResult<AutoPrePickConfirm>> PrePickConfirm(string message = null);

        [Get("/report/Dashboard/PrePickConfirm2")]
        Task<PageResult<AutoPrePickConfirm>> PrePickConfirm2(string message = null);

        [Get("/report/Dashboard/PrePickConfirm3")]
        Task<PageResult<AutoPrePickConfirm>> PrePickConfirm3(string messageInfo = null);

        [Get("/report/Dashboard/GetDbTj")]
        Task<PageResult<PlanTaskModel>> GetDbTj(string bayId = null);

        [Get("/report/Dashboard/GetDbTjBC")]
        Task<PageResult<List<int>>> GetDbTjBC(string bayId = null);

        [Get("/report/Dashboard/Is2andBy1FloorAvaliable")]
        Task<bool> Is2andBy1FloorAvaliable(string locationName = null);

        [Get("/report/Dashboard/Is2andBy1FloorAvaliable111")]
        Task<bool> Is2andBy1FloorAvaliable111();

        [Get("/report/Dashboard/GetAuto1list")]
        Task<PageResult<int>> GetAuto1list(string bayCode = null, string time = null);

        [Get("/report/Dashboard/GetAuto2list")]
        Task<PageResult<int>> GetAuto2list(string bayCode = null, string time = null);

        [Get("/report/Dashboard/GetAuto3list")]
        Task<PageResult<int>> GetAuto3list(string bayCode = null, string time = null);

        [Get("/report/Dashboard/GetCraneTaskTime")]
        Task<PageResult<int>> GetCraneTaskTime(string bayName = null);

        [Get("/report/Dashboard/GetCranePlanTime")]
        Task<PageResult<int>> GetCranePlanTime(string bayName = null, string type = null);

        [Get("/report/Dashboard/Get/{id}")]
        Task<TRcLogReadModel> Get(string id);

        [Get("/report/Dashboard/GetPage")]
        Task<PageResult<TRcLogReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/Dashboard/GetPageByString")]
        Task<PageResult<TRcLogReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/Dashboard/GetListByString")]
        Task<PageResult<TRcLogReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/Dashboard/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/Dashboard/GetList")]
        Task<PageResult<TRcLogReadModel>> GetList();
    }
}