//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcTrainNodeApi
    {
        [Post("/report/TRcTrainNode/Create")]
        Task<OperationResult> Create([Body] TRcTrainNodeCreateModel createModel);

        [Put("/report/TRcTrainNode/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTrainNodeUpdateModel updateModel);

        [Delete("/report/TRcTrainNode/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcTrainNode/Get/{id}")]
        Task<TRcTrainNodeReadModel> Get(string id);

        [Get("/report/TRcTrainNode/GetPage")]
        Task<PageResult<TRcTrainNodeReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTrainNode/GetPageByString")]
        Task<PageResult<TRcTrainNodeReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTrainNode/GetListByString")]
        Task<PageResult<TRcTrainNodeReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTrainNode/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTrainNode/GetList")]
        Task<PageResult<TRcTrainNodeReadModel>> GetList();
    }
}