//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcTelegramApi
    {
        [Post("/report/TRcTelegram/Create")]
        Task<OperationResult> Create([Body] TRcTelegramCreateModel createModel);

        [Put("/report/TRcTelegram/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTelegramUpdateModel updateModel);

        [Delete("/report/TRcTelegram/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcTelegram/Get/{id}")]
        Task<TRcTelegramReadModel> Get(string id);

        [Get("/report/TRcTelegram/GetPage")]
        Task<PageResult<TRcTelegramReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTelegram/GetPageByString")]
        Task<PageResult<TRcTelegramReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTelegram/GetListByString")]
        Task<PageResult<TRcTelegramReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTelegram/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTelegram/GetList")]
        Task<PageResult<TRcTelegramReadModel>> GetList();
    }
}