//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcTruckLoadingLogApi
    {
        [Post("/report/TRcTruckLoadingLog/Create")]
        Task<OperationResult> Create([Body] TRcTruckLoadingLogCreateModel createModel);

        [Put("/report/TRcTruckLoadingLog/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTruckLoadingLogUpdateModel updateModel);

        [Delete("/report/TRcTruckLoadingLog/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcTruckLoadingLog/Get/{id}")]
        Task<TRcTruckLoadingLogReadModel> Get(string id);

        [Get("/report/TRcTruckLoadingLog/GetPage")]
        Task<PageResult<TRcTruckLoadingLogReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTruckLoadingLog/GetPageByString")]
        Task<PageResult<TRcTruckLoadingLogReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTruckLoadingLog/GetListByString")]
        Task<PageResult<TRcTruckLoadingLogReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTruckLoadingLog/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTruckLoadingLog/GetList")]
        Task<PageResult<TRcTruckLoadingLogReadModel>> GetList();
    }
}