//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public partial interface ITRcMaterialApi
    {
        [Post("/report/TRcMaterial/Create")]
        Task<OperationResult> Create([Body] TRcMaterialCreateModel createModel);

        [Put("/report/TRcMaterial/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcMaterialUpdateModel updateModel);

        [Delete("/report/TRcMaterial/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/report/TRcMaterial/Get/{id}")]
        Task<TRcMaterialReadModel> Get(string id);

        [Get("/report/TRcMaterial/GetPage")]
        Task<PageResult<TRcMaterialReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcMaterial/GetPageByString")]
        Task<PageResult<TRcMaterialReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcMaterial/GetListByString")]
        Task<PageResult<TRcMaterialReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcMaterial/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcMaterial/GetList")]
        Task<PageResult<TRcMaterialReadModel>> GetList();
    }
}