//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcTrainDeliveryPickApi
    {
        [Post("/report/TRcTrainDeliveryPick/Create")]
        Task<OperationResult> Create([Body] TRcTrainDeliveryPickCreateModel createModel);

        [Put("/report/TRcTrainDeliveryPick/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTrainDeliveryPickUpdateModel updateModel);

        [Delete("/report/TRcTrainDeliveryPick/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcTrainDeliveryPick/Get/{id}")]
        Task<TRcTrainDeliveryPickReadModel> Get(string id);

        [Get("/report/TRcTrainDeliveryPick/GetPage")]
        Task<PageResult<TRcTrainDeliveryPickReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTrainDeliveryPick/GetPageByString")]
        Task<PageResult<TRcTrainDeliveryPickReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTrainDeliveryPick/GetListByString")]
        Task<PageResult<TRcTrainDeliveryPickReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTrainDeliveryPick/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTrainDeliveryPick/GetList")]
        Task<PageResult<TRcTrainDeliveryPickReadModel>> GetList();
    }
}