//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcLocationsRateApi
    {
        [Get("/report/TRcLocationsRate/GetPageBySearchTime")]
        Task<PageResult<TRcLocationsRateReadModel>> GetPageBySearchTime(int? current = null, int? pageSize = null, [Query] string[] dt = null, [Query] string[] bayCode = null, string orders = null);

        [Post("/report/TRcLocationsRate/Create")]
        Task<OperationResult> Create([Body] TRcLocationsRateCreateModel createModel);

        [Put("/report/TRcLocationsRate/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcLocationsRateUpdateModel updateModel);

        [Delete("/report/TRcLocationsRate/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcLocationsRate/Get/{id}")]
        Task<TRcLocationsRateReadModel> Get(string id);

        [Get("/report/TRcLocationsRate/GetPage")]
        Task<PageResult<TRcLocationsRateReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcLocationsRate/GetPageByString")]
        Task<PageResult<TRcLocationsRateReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcLocationsRate/GetListByString")]
        Task<PageResult<TRcLocationsRateReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcLocationsRate/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcLocationsRate/GetList")]
        Task<PageResult<TRcLocationsRateReadModel>> GetList();
    }
}