//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Report.WmsApi
{
    public interface ITRcTrainDeliveryApi
    {
        [Post("/report/TRcTrainDelivery/Create")]
        Task<OperationResult> Create([Body] TRcTrainDeliveryCreateModel createModel);

        [Put("/report/TRcTrainDelivery/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcTrainDeliveryUpdateModel updateModel);

        [Delete("/report/TRcTrainDelivery/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcTrainDelivery/Get/{id}")]
        Task<TRcTrainDeliveryReadModel> Get(string id);

        [Get("/report/TRcTrainDelivery/GetPage")]
        Task<PageResult<TRcTrainDeliveryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcTrainDelivery/GetPageByString")]
        Task<PageResult<TRcTrainDeliveryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcTrainDelivery/GetListByString")]
        Task<PageResult<TRcTrainDeliveryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcTrainDelivery/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcTrainDelivery/GetList")]
        Task<PageResult<TRcTrainDeliveryReadModel>> GetList();
    }
}