//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITRlDispatchRulesApi
    {
        [Post("/admin/TRlDispatchRules/Create")]
        Task<OperationResult> Create([Body] TRlDispatchRulesCreateModel createModel);

        [Put("/admin/TRlDispatchRules/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlDispatchRulesUpdateModel updateModel);

        [Delete("/admin/TRlDispatchRules/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TRlDispatchRules/Get/{id}")]
        Task<TRlDispatchRulesReadModel> Get(string id);

        [Get("/admin/TRlDispatchRules/GetPage")]
        Task<PageResult<TRlDispatchRulesReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlDispatchRules/GetPageByString")]
        Task<PageResult<TRlDispatchRulesReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlDispatchRules/GetListByString")]
        Task<PageResult<TRlDispatchRulesReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlDispatchRules/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlDispatchRules/GetList")]
        Task<PageResult<TRlDispatchRulesReadModel>> GetList();
    }
}