//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITRlCranePlanTypeApi
    {
        [Put("/admin/TRlCranePlanType/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlCranePlanTypeUpdateModel updateModel);

        [Post("/admin/TRlCranePlanType/Create")]
        Task<OperationResult> Create([Body] TRlCranePlanTypeCreateModel createModel);

        [Delete("/admin/TRlCranePlanType/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TRlCranePlanType/Get/{id}")]
        Task<TRlCranePlanTypeReadModel> Get(string id);

        [Get("/admin/TRlCranePlanType/GetPage")]
        Task<PageResult<TRlCranePlanTypeReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlCranePlanType/GetPageByString")]
        Task<PageResult<TRlCranePlanTypeReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlCranePlanType/GetListByString")]
        Task<PageResult<TRlCranePlanTypeReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlCranePlanType/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlCranePlanType/GetList")]
        Task<PageResult<TRlCranePlanTypeReadModel>> GetList();
    }
}