//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITRlTransferPrewiredApi
    {
        [Post("/admin/TRlTransferPrewired/Create")]
        Task<OperationResult> Create([Body] TRlTransferPrewiredCreateModel createModel);

        [Put("/admin/TRlTransferPrewired/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlTransferPrewiredUpdateModel updateModel);

        [Delete("/admin/TRlTransferPrewired/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TRlTransferPrewired/Get/{id}")]
        Task<TRlTransferPrewiredReadModel> Get(string id);

        [Get("/admin/TRlTransferPrewired/GetPage")]
        Task<PageResult<TRlTransferPrewiredReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlTransferPrewired/GetPageByString")]
        Task<PageResult<TRlTransferPrewiredReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlTransferPrewired/GetListByString")]
        Task<PageResult<TRlTransferPrewiredReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlTransferPrewired/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlTransferPrewired/GetList")]
        Task<PageResult<TRlTransferPrewiredReadModel>> GetList();
    }
}