//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITRlLocationApi
    {
        [Post("/admin/TRlLocation/Create")]
        Task<OperationResult> Create([Body] TRlLocationCreateModel createModel);

        [Put("/admin/TRlLocation/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlLocationUpdateModel updateModel);

        [Delete("/admin/TRlLocation/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TRlLocation/Get/{id}")]
        Task<TRlLocationReadModel> Get(string id);

        [Get("/admin/TRlLocation/GetPage")]
        Task<PageResult<TRlLocationReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlLocation/GetPageByString")]
        Task<PageResult<TRlLocationReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlLocation/GetListByString")]
        Task<PageResult<TRlLocationReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlLocation/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlLocation/GetList")]
        Task<PageResult<TRlLocationReadModel>> GetList();
    }
}