//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITRlLocationAssignApi
    {
        [Put("/admin/TRlLocationAssign/UpdateAssign")]
        Task<OperationResult> UpdateAssign(string id = null);

        [Post("/admin/TRlLocationAssign/Create")]
        Task<OperationResult> Create([Body] TRlLocationAssignCreateModel createModel);

        [Put("/admin/TRlLocationAssign/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlLocationAssignUpdateModel updateModel);

        [Delete("/admin/TRlLocationAssign/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TRlLocationAssign/Get/{id}")]
        Task<TRlLocationAssignReadModel> Get(string id);

        [Get("/admin/TRlLocationAssign/GetPage")]
        Task<PageResult<TRlLocationAssignReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlLocationAssign/GetPageByString")]
        Task<PageResult<TRlLocationAssignReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlLocationAssign/GetListByString")]
        Task<PageResult<TRlLocationAssignReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlLocationAssign/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlLocationAssign/GetList")]
        Task<PageResult<TRlLocationAssignReadModel>> GetList();
    }
}