//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITRlRegionRangeApi
    {
        [Post("/admin/TRlRegionRange/Create")]
        Task<OperationResult> Create([Body] TRlRegionRangeCreateModel createModel);

        [Put("/admin/TRlRegionRange/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRlRegionRangeUpdateModel updateModel);

        [Delete("/admin/TRlRegionRange/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TRlRegionRange/Get/{id}")]
        Task<TRlRegionRangeReadModel> Get(string id);

        [Get("/admin/TRlRegionRange/GetPage")]
        Task<PageResult<TRlRegionRangeReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TRlRegionRange/GetPageByString")]
        Task<PageResult<TRlRegionRangeReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TRlRegionRange/GetListByString")]
        Task<PageResult<TRlRegionRangeReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TRlRegionRange/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TRlRegionRange/GetList")]
        Task<PageResult<TRlRegionRangeReadModel>> GetList();
    }
}