//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITScDictionaryApi
    {
        /// <summary>
        /// 获取所有owner为空（即字典分类）的数据列表
        /// </summary>
        /// <param name="ownerValue"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/admin/TScDictionary/GetAllClassList")]
        Task<PageResult<TScDictionaryReadModel>> GetAllClassList();

        [Get("/admin/TScDictionary/GetListQuery")]
        Task<PageResult<TScDictionaryReadModel>> GetListQuery([Query] string[] ownerValue = null);

        /// <summary>
        /// 各库产线列表
        /// </summary>
        [Get("/admin/TScDictionary/GetChainPage")]
        Task<PageResult<TScDictionaryReadModel>> GetChainPage(string bayName = null);

        [Post("/admin/TScDictionary/Create")]
        Task<OperationResult> Create([Body] TScDictionaryCreateModel createModel);

        [Put("/admin/TScDictionary/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScDictionaryUpdateModel updateModel);

        [Delete("/admin/TScDictionary/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TScDictionary/Get/{id}")]
        Task<TScDictionaryReadModel> Get(string id);

        [Get("/admin/TScDictionary/GetPage")]
        Task<PageResult<TScDictionaryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScDictionary/GetPageByString")]
        Task<PageResult<TScDictionaryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScDictionary/GetListByString")]
        Task<PageResult<TScDictionaryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScDictionary/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScDictionary/GetList")]
        Task<PageResult<TScDictionaryReadModel>> GetList();
    }
}