//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITScAppApi
    {
        [Get("/admin/TScApp/GetHoldApp")]
        Task<TScAppReadModel> GetHoldApp();

        [Get("/admin/TScApp/GetCraneApp")]
        Task<TScAppReadModel> GetCraneApp();

        [Post("/admin/TScApp/Create")]
        Task<OperationResult> Create([Body] TScAppCreateModel createModel);

        [Put("/admin/TScApp/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScAppUpdateModel updateModel);

        [Delete("/admin/TScApp/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TScApp/Get/{id}")]
        Task<TScAppReadModel> Get(string id);

        [Get("/admin/TScApp/GetPage")]
        Task<PageResult<TScAppReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScApp/GetPageByString")]
        Task<PageResult<TScAppReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScApp/GetListByString")]
        Task<PageResult<TScAppReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScApp/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScApp/GetList")]
        Task<PageResult<TScAppReadModel>> GetList();
    }
}