//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITScTransferSpecApi
    {
        [Post("/admin/TScTransferSpec/GetAllTransferSpecLeft")]
        Task<OperationResult<List<TScTransferSpecReadModel>>> GetAllTransferSpecLeft(int? belongSpecWidth = null);

        [Post("/admin/TScTransferSpec/GetAllTransferSpecRight")]
        Task<OperationResult<List<TScTransferSpecReadModel>>> GetAllTransferSpecRight(int? belongSpecWidth = null, int? specWidth = null);

        [Post("/admin/TScTransferSpec/Create")]
        Task<OperationResult> Create([Body] TScTransferSpecCreateModel createModel);

        [Put("/admin/TScTransferSpec/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScTransferSpecUpdateModel updateModel);

        [Delete("/admin/TScTransferSpec/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TScTransferSpec/Get/{id}")]
        Task<TScTransferSpecReadModel> Get(string id);

        [Get("/admin/TScTransferSpec/GetPage")]
        Task<PageResult<TScTransferSpecReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScTransferSpec/GetPageByString")]
        Task<PageResult<TScTransferSpecReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScTransferSpec/GetListByString")]
        Task<PageResult<TScTransferSpecReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScTransferSpec/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScTransferSpec/GetList")]
        Task<PageResult<TScTransferSpecReadModel>> GetList();
    }
}