//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITScDictionaryApi
    {
        [Get("/admin/TScDictionary/GetAllClassList")]
        Task<PageResult<TScDictionaryReadModel>> GetAllClassList();

        [Get("/admin/TScDictionary/GetListQuery")]
        Task<PageResult<TScDictionaryReadModel>> GetListQuery(string[] ownerValue = null);

        [Get("/admin/TScDictionary/GetChainPage")]
        Task<PageResult<TScDictionaryReadModel>> GetChainPage(string bayName = null);

        [Post("/admin/TScDictionary/Create")]
        Task<OperationResult> Create([Body] TScDictionaryCreateModel createModel);

        [Put("/admin/TScDictionary/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScDictionaryUpdateModel updateModel);

        [Delete("/admin/TScDictionary/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TScDictionary/Get/{id}")]
        Task<TScDictionaryReadModel> Get(string id);

        [Get("/admin/TScDictionary/GetPage")]
        Task<PageResult<TScDictionaryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScDictionary/GetPageByString")]
        Task<PageResult<TScDictionaryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScDictionary/GetListByString")]
        Task<PageResult<TScDictionaryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScDictionary/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScDictionary/GetList")]
        Task<PageResult<TScDictionaryReadModel>> GetList();
    }
}