//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITScColorApi
    {
        [Post("/admin/TScColor/Create")]
        Task<OperationResult> Create([Body] TScColorCreateModel createModel);

        [Put("/admin/TScColor/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScColorUpdateModel updateModel);

        [Delete("/admin/TScColor/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TScColor/Get/{id}")]
        Task<TScColorReadModel> Get(string id);

        [Get("/admin/TScColor/GetPage")]
        Task<PageResult<TScColorReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScColor/GetPageByString")]
        Task<PageResult<TScColorReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScColor/GetListByString")]
        Task<PageResult<TScColorReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScColor/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScColor/GetList")]
        Task<PageResult<TScColorReadModel>> GetList();
    }
}