//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITScClientApi
    {
        [Post("/admin/TScClient/Create")]
        Task<OperationResult> Create([Body] TScClientCreateModel createModel);

        [Put("/admin/TScClient/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TScClientUpdateModel updateModel);

        [Delete("/admin/TScClient/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TScClient/Get/{id}")]
        Task<TScClientReadModel> Get(string id);

        [Get("/admin/TScClient/GetPage")]
        Task<PageResult<TScClientReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TScClient/GetPageByString")]
        Task<PageResult<TScClientReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TScClient/GetListByString")]
        Task<PageResult<TScClientReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TScClient/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TScClient/GetList")]
        Task<PageResult<TScClientReadModel>> GetList();
    }
}