//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITUmUserApi
    {
        [Get("/admin/TUmUser/GetPageQuery")]
        Task<PageResult<TUmUserReadModel>> GetPageQuery(int? current = null, int? pageSize = null, string account = null, string name = null, string department = null, string[] teamName = null);

        [Get("/admin/TUmUser/GetUserInfo")]
        Task<PageResult<TUmUserReadModel>> GetUserInfo([Body] TUmUserReadModel user);

        [Post("/admin/TUmUser/Create")]
        Task<OperationResult> Create([Body] TUmUserCreateModel createModel);

        [Put("/admin/TUmUser/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmUserUpdateModel updateModel);

        [Delete("/admin/TUmUser/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TUmUser/Get/{id}")]
        Task<TUmUserReadModel> Get(string id);

        [Get("/admin/TUmUser/GetPage")]
        Task<PageResult<TUmUserReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmUser/GetPageByString")]
        Task<PageResult<TUmUserReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmUser/GetListByString")]
        Task<PageResult<TUmUserReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmUser/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmUser/GetList")]
        Task<PageResult<TUmUserReadModel>> GetList();
    }
}