//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITUmRolePermissionApi
    {
        /// <summary>
        /// 获取所有的菜单列表
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/admin/TUmRolePermission/GetAllListQuery")]
        Task<PageResult<TUmMenuReadModel>> GetAllListQuery(string roleId = null);

        /// <summary>
        /// 获取所有的菜单列表
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Post("/admin/TUmRolePermission/AddRolePermissonList")]
        Task<PageResult<TUmMenuReadModel>> AddRolePermissonList([Body] string[] permissions, string roleId = null);

        [Post("/admin/TUmRolePermission/Create")]
        Task<OperationResult> Create([Body] TUmRolePermissionCreateModel createModel);

        [Put("/admin/TUmRolePermission/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmRolePermissionUpdateModel updateModel);

        [Delete("/admin/TUmRolePermission/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TUmRolePermission/Get/{id}")]
        Task<TUmRolePermissionReadModel> Get(string id);

        [Get("/admin/TUmRolePermission/GetPage")]
        Task<PageResult<TUmRolePermissionReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmRolePermission/GetPageByString")]
        Task<PageResult<TUmRolePermissionReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmRolePermission/GetListByString")]
        Task<PageResult<TUmRolePermissionReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmRolePermission/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmRolePermission/GetList")]
        Task<PageResult<TUmRolePermissionReadModel>> GetList();
    }
}