//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITUmColSetApi
    {
        [Post("/admin/TUmColSet/Create")]
        Task<OperationResult> Create([Body] TUmColSetCreateModel createModel);

        [Put("/admin/TUmColSet/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmColSetUpdateModel updateModel);

        [Delete("/admin/TUmColSet/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TUmColSet/Get/{id}")]
        Task<TUmColSetReadModel> Get(string id);

        [Get("/admin/TUmColSet/GetPage")]
        Task<PageResult<TUmColSetReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmColSet/GetPageByString")]
        Task<PageResult<TUmColSetReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmColSet/GetListByString")]
        Task<PageResult<TUmColSetReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmColSet/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmColSet/GetList")]
        Task<PageResult<TUmColSetReadModel>> GetList();
    }
}