//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITUmPermissionApi
    {
        [Post("/admin/TUmPermission/Create")]
        Task<OperationResult> Create([Body] TUmPermissionCreateModel createModel);

        [Put("/admin/TUmPermission/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmPermissionUpdateModel updateModel);

        [Delete("/admin/TUmPermission/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TUmPermission/Get/{id}")]
        Task<TUmPermissionReadModel> Get(string id);

        [Get("/admin/TUmPermission/GetPage")]
        Task<PageResult<TUmPermissionReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmPermission/GetPageByString")]
        Task<PageResult<TUmPermissionReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmPermission/GetListByString")]
        Task<PageResult<TUmPermissionReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmPermission/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmPermission/GetList")]
        Task<PageResult<TUmPermissionReadModel>> GetList();
    }
}