//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public partial interface ITUmShiftApi
    {
        [Post("/admin/TUmShift/Create")]
        Task<OperationResult> Create([Body] TUmShiftCreateModel createModel);

        [Put("/admin/TUmShift/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmShiftUpdateModel updateModel);

        [Delete("/admin/TUmShift/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/admin/TUmShift/Get/{id}")]
        Task<TUmShiftReadModel> Get(string id);

        [Get("/admin/TUmShift/GetPage")]
        Task<PageResult<TUmShiftReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmShift/GetPageByString")]
        Task<PageResult<TUmShiftReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmShift/GetListByString")]
        Task<PageResult<TUmShiftReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmShift/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmShift/GetList")]
        Task<PageResult<TUmShiftReadModel>> GetList();
    }
}