//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITUmRoleApi
    {
        /// <summary>
        /// 获取所有的角色列表
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/admin/TUmRole/GetAllList")]
        Task<PageResult<TUmRoleReadModel>> GetAllList(string order = null);

        [Post("/admin/TUmRole/Create")]
        Task<OperationResult> Create([Body] TUmRoleCreateModel createModel);

        [Put("/admin/TUmRole/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmRoleUpdateModel updateModel);

        [Delete("/admin/TUmRole/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TUmRole/Get/{id}")]
        Task<TUmRoleReadModel> Get(string id);

        [Get("/admin/TUmRole/GetPage")]
        Task<PageResult<TUmRoleReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmRole/GetPageByString")]
        Task<PageResult<TUmRoleReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmRole/GetListByString")]
        Task<PageResult<TUmRoleReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmRole/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmRole/GetList")]
        Task<PageResult<TUmRoleReadModel>> GetList();
    }
}