//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Admin
{
    public interface ITUmMenuApi
    {
        /// <summary>
        /// 获取所有ownerid为空（即菜单文件夹）的数据列表
        /// </summary>
        [Get("/admin/TUmMenu/GetAllFolderList")]
        Task<PageResult<TUmMenuReadModel>> GetAllFolderList();

        /// <summary>
        /// 获取所有的菜单列表
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Get("/admin/TUmMenu/GetAllList")]
        Task<PageResult<TUmMenuReadModel>> GetAllList();

        [Post("/admin/TUmMenu/Create")]
        Task<OperationResult> Create([Body] TUmMenuCreateModel createModel);

        [Put("/admin/TUmMenu/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TUmMenuUpdateModel updateModel);

        [Delete("/admin/TUmMenu/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/admin/TUmMenu/Get/{id}")]
        Task<TUmMenuReadModel> Get(string id);

        [Get("/admin/TUmMenu/GetPage")]
        Task<PageResult<TUmMenuReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/admin/TUmMenu/GetPageByString")]
        Task<PageResult<TUmMenuReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/admin/TUmMenu/GetListByString")]
        Task<PageResult<TUmMenuReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/admin/TUmMenu/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/admin/TUmMenu/GetList")]
        Task<PageResult<TUmMenuReadModel>> GetList();
    }
}