//<auto-generated />

using System;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;
using WmsApi.Contracts.Models;

namespace WmsApi.Report
{
    public interface ITRcInventoryApi
    {
        /// <summary>
        /// 手持获取批次号
        /// </summary>
        /// <returns></returns>
        [Get("/report/TRcInventory/GetAllPlanNo")]
        Task<PageResult<TRcInventoryReadModel>> GetAllPlanNo(string bayId = null);

        /// <summary>
        /// 客户端获取批次号
        /// </summary>
        [Get("/report/TRcInventory/GetPlanNo")]
        Task<PageResult<TRcInventoryReadModel>> GetPlanNo(DateTime? startTime = null, DateTime? endTime = null);

        /// <summary>
        /// 创建盘库批次号
        /// </summary>
        /// <returns></returns>
        [Get("/report/TRcInventory/AddAllPlanNo")]
        Task<ItemResult<TRcInventoryReadModel>> AddAllPlanNo(string bayId = null);

        [Post("/report/TRcInventory/Create")]
        Task<OperationResult> Create([Body] TRcInventoryCreateModel createModel);

        [Put("/report/TRcInventory/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TRcInventoryUpdateModel updateModel);

        [Delete("/report/TRcInventory/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/report/TRcInventory/Get/{id}")]
        Task<TRcInventoryReadModel> Get(string id);

        [Get("/report/TRcInventory/GetPage")]
        Task<PageResult<TRcInventoryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/report/TRcInventory/GetPageByString")]
        Task<PageResult<TRcInventoryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/report/TRcInventory/GetListByString")]
        Task<PageResult<TRcInventoryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/report/TRcInventory/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/report/TRcInventory/GetList")]
        Task<PageResult<TRcInventoryReadModel>> GetList();
    }
}