//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlCraneMaintenanceApi
    {
        [Post("/plan/TPlCraneMaintenance/CreatePlan")]
        Task<OperationResult> CreatePlan([Body] TPlCraneMaintenanceCreateModel createModel);

        [Post("/plan/TPlCraneMaintenance/Apply")]
        Task<OperationResult> Apply(string id = null);

        [Post("/plan/TPlCraneMaintenance/Purge")]
        Task<OperationResult> Purge(string id = null);

        [Post("/plan/TPlCraneMaintenance/Create")]
        Task<OperationResult> Create([Body] TPlCraneMaintenanceCreateModel createModel);

        [Put("/plan/TPlCraneMaintenance/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlCraneMaintenanceUpdateModel updateModel);

        [Delete("/plan/TPlCraneMaintenance/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlCraneMaintenance/Get/{id}")]
        Task<TPlCraneMaintenanceReadModel> Get(string id);

        [Get("/plan/TPlCraneMaintenance/GetPage")]
        Task<PageResult<TPlCraneMaintenanceReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlCraneMaintenance/GetPageByString")]
        Task<PageResult<TPlCraneMaintenanceReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlCraneMaintenance/GetListByString")]
        Task<PageResult<TPlCraneMaintenanceReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlCraneMaintenance/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlCraneMaintenance/GetList")]
        Task<PageResult<TPlCraneMaintenanceReadModel>> GetList();
    }
}