//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTrainDeliveryApi
    {
        [Post("/plan/TPlTrainDelivery/Create")]
        Task<OperationResult> Create([Body] TPlTrainDeliveryCreateModel createModel);

        [Put("/plan/TPlTrainDelivery/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTrainDeliveryUpdateModel updateModel);

        [Delete("/plan/TPlTrainDelivery/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTrainDelivery/Get/{id}")]
        Task<TPlTrainDeliveryReadModel> Get(string id);

        [Get("/plan/TPlTrainDelivery/GetPage")]
        Task<PageResult<TPlTrainDeliveryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTrainDelivery/GetPageByString")]
        Task<PageResult<TPlTrainDeliveryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTrainDelivery/GetListByString")]
        Task<PageResult<TPlTrainDeliveryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTrainDelivery/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTrainDelivery/GetList")]
        Task<PageResult<TPlTrainDeliveryReadModel>> GetList();
    }
}