//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlStackTranferApi
    {
        [Post("/plan/TPlStackTranfer/CreateStack")]
        Task<OperationResult> CreateStack([Body] TPlStackTranferCreateModel createModel);

        [Put("/plan/TPlStackTranfer/UpdateStack/{id}")]
        Task<OperationResult> UpdateStack(string id, [Body] TPlStackTranferUpdateModel updateModel);

        [Delete("/plan/TPlStackTranfer/DeleteStack")]
        Task<OperationResult> DeleteStack([Query] string[] ids = null);

        /// <summary>
        /// 批量启用/禁用
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlStackTranfer/UpdateIsabled")]
        Task<OperationResult> UpdateIsabled([Query] string[] ids = null, int? isEnable = null);

        /// <summary>
        /// 批量重置
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlStackTranfer/UpdateReset")]
        Task<OperationResult> UpdateReset([Query] string[] ids = null);

        [Post("/plan/TPlStackTranfer/Create")]
        Task<OperationResult> Create([Body] TPlStackTranferCreateModel createModel);

        [Put("/plan/TPlStackTranfer/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlStackTranferUpdateModel updateModel);

        [Delete("/plan/TPlStackTranfer/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlStackTranfer/Get/{id}")]
        Task<TPlStackTranferReadModel> Get(string id);

        [Get("/plan/TPlStackTranfer/GetPage")]
        Task<PageResult<TPlStackTranferReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlStackTranfer/GetPageByString")]
        Task<PageResult<TPlStackTranferReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlStackTranfer/GetListByString")]
        Task<PageResult<TPlStackTranferReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlStackTranfer/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlStackTranfer/GetList")]
        Task<PageResult<TPlStackTranferReadModel>> GetList();
    }
}