//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlBayTransferApi
    {
        /// <summary>
        /// 客户端创建库间倒运计划
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlBayTransfer/CreateTransferPlan")]
        Task<OperationResult> CreateTransferPlan([Body] TPlBayTransferCreateModel createModel);

        /// <summary>
        /// 发送倒运信息
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlBayTransfer/SendTransferInfo")]
        Task<ItemResult<TPlBayTransferReadModel>> SendTransferInfo(string materialNo = null, string location = null);

        /// <summary>
        /// 导入倒运钢卷信息
        /// </summary>
        /// <returns></returns>
        [Multipart]
        [Post("/plan/TPlBayTransfer/ImportBayTransferData")]
        Task<OperationResult<List<string>>> ImportBayTransferData(MultipartItem file);

        /// <summary>
        /// 手持创建电瓶车库间倒运计划
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlBayTransfer/HoldCreateTransferPlan")]
        Task<AddScanDetailResult> HoldCreateTransferPlan(string vehicleId = null, string material = null, string fromBayName = null, string destBayName = null);

        /// <summary>
        /// 查询电瓶车计划
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlBayTransfer/GetTransferPlan")]
        Task<List<TransferPlanModel>> GetTransferPlan(string vehicleId = null);

        /// <summary>
        /// 手持删除电瓶车倒运计划
        /// </summary>
        /// <returns></returns>
        [Put("/plan/TPlBayTransfer/HoldDeleteTransferPlan")]
        Task<OperationResult> HoldDeleteTransferPlan(string vehicleId = null, string material = null);

        /// <summary>
        /// 判断计划不唯一
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlBayTransfer/CreatePlanCondition")]
        Task<OperationResult> CreatePlanCondition(string vehicleTypeId = null);

        /// <summary>
        /// 更新库间倒运计划
        /// </summary>
        /// <returns></returns>
        [Post("/plan/TPlBayTransfer/UpdateTransferPlan")]
        Task<OperationResult> UpdateTransferPlan([Body] TPlBayTransferUpdateModel updateModel);

        /// <summary>
        /// 删除库间倒运计划
        /// </summary>
        /// <param name="ids"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Delete("/plan/TPlBayTransfer/DeleteTransferPlan")]
        Task<OperationResult> DeleteTransferPlan([Query] string[] ids = null);

        [Post("/plan/TPlBayTransfer/Create")]
        Task<OperationResult> Create([Body] TPlBayTransferCreateModel createModel);

        [Put("/plan/TPlBayTransfer/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlBayTransferUpdateModel updateModel);

        [Delete("/plan/TPlBayTransfer/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlBayTransfer/Get/{id}")]
        Task<TPlBayTransferReadModel> Get(string id);

        [Get("/plan/TPlBayTransfer/GetPage")]
        Task<PageResult<TPlBayTransferReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlBayTransfer/GetPageByString")]
        Task<PageResult<TPlBayTransferReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlBayTransfer/GetListByString")]
        Task<PageResult<TPlBayTransferReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlBayTransfer/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlBayTransfer/GetList")]
        Task<PageResult<TPlBayTransferReadModel>> GetList();
    }
}