//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTruckLoadListPreApi
    {
        [Get("/plan/TPlTruckLoadListPre/GetAllLoadingNos_old")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetAllLoadingNos_old(int? current = null, int? pageSize = null, string vehicleNo = null, int[] resolveState = null, string[] sourceHouse = null);

        [Get("/plan/TPlTruckLoadListPre/GetAllLoadingNos")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetAllLoadingNos(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckLoadListPre/GetAllUnpicked_old")]
        Task<OperationResult<List<VPlMaterialReadModel>>> GetAllUnpicked_old(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null);

        [Post("/plan/TPlTruckLoadListPre/GetAllUnpicked")]
        Task<OperationResult<List<VPlMaterialReadModel>>> GetAllUnpicked(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckLoadListPre/GetAllPicked_old")]
        Task<PageResult<VPlMaterialReadModel>> GetAllPicked_old(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null);

        [Post("/plan/TPlTruckLoadListPre/GetAllPicked")]
        Task<PageResult<VPlMaterialReadModel>> GetAllPicked(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckLoadListPre/Pick")]
        Task<OperationResult> Pick(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null, string[] materialNos = null);

        [Post("/plan/TPlTruckLoadListPre/Unpick")]
        Task<OperationResult> Unpick(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null, string[] materialNos = null);

        [Post("/plan/TPlTruckLoadListPre/Confirm")]
        Task<OperationResult> Confirm(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null);

        [Post("/plan/TPlTruckLoadListPre/Cancel")]
        Task<OperationResult> Cancel(string truckLoadingNo = null, string detailNo = null);

        [Post("/plan/TPlTruckLoadListPre/AutoPrePick")]
        Task<OperationResult> AutoPrePick(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null);

        [Get("/plan/TPlTruckLoadListPre/GetTheAutomaticLoadingRatio")]
        Task<PageResult<int>> GetTheAutomaticLoadingRatio(string[] time = null);

        [Post("/plan/TPlTruckLoadListPre/Create")]
        Task<OperationResult> Create([Body] TPlTruckLoadListCreateModel createModel);

        [Put("/plan/TPlTruckLoadListPre/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckLoadListUpdateModel updateModel);

        [Delete("/plan/TPlTruckLoadListPre/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTruckLoadListPre/Get/{id}")]
        Task<TPlTruckLoadListReadModel> Get(string id);

        [Get("/plan/TPlTruckLoadListPre/GetPage")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckLoadListPre/GetPageByString")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckLoadListPre/GetListByString")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckLoadListPre/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckLoadListPre/GetList")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetList();
    }
}