//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlFinishLineApi
    {
        /// <summary>
        /// 获取上料机组
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlFinishLine/GetLine")]
        Task<PageResult<TPlFinishLineReadModel>> GetLine();

        /// <summary>
        /// 获取生产计划号
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlFinishLine/GetStockPlan")]
        Task<PageResult<TPlFinishLineReadModel>> GetStockPlan(string lineNo = null);

        /// <summary>
        /// 上料计划钢卷列表
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlFinishLine/GetAllStockList")]
        Task<List<TTrLocationMaterialReadModel>> GetAllStockList(string planNo = null);

        /// <summary>
        /// 精整上料
        /// </summary>
        /// <param name="materialNo"></param>
        /// <returns></returns>
        [Post("/plan/TPlFinishLine/LoadMaterial")]
        Task<OperationResult> LoadMaterial(string materialNo = null);

        [Post("/plan/TPlFinishLine/Create")]
        Task<OperationResult> Create([Body] TPlFinishLineCreateModel createModel);

        [Put("/plan/TPlFinishLine/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlFinishLineUpdateModel updateModel);

        [Delete("/plan/TPlFinishLine/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlFinishLine/Get/{id}")]
        Task<TPlFinishLineReadModel> Get(string id);

        [Get("/plan/TPlFinishLine/GetPage")]
        Task<PageResult<TPlFinishLineReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlFinishLine/GetPageByString")]
        Task<PageResult<TPlFinishLineReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlFinishLine/GetListByString")]
        Task<PageResult<TPlFinishLineReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlFinishLine/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlFinishLine/GetList")]
        Task<PageResult<TPlFinishLineReadModel>> GetList();
    }
}