//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTruckBackApi
    {
        [Post("/plan/TPlTruckBack/Create")]
        Task<OperationResult> Create([Body] TPlTruckBackCreateModel createModel);

        [Put("/plan/TPlTruckBack/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckBackUpdateModel updateModel);

        [Delete("/plan/TPlTruckBack/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTruckBack/Get/{id}")]
        Task<TPlTruckBackReadModel> Get(string id);

        [Get("/plan/TPlTruckBack/GetPage")]
        Task<PageResult<TPlTruckBackReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckBack/GetPageByString")]
        Task<PageResult<TPlTruckBackReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckBack/GetListByString")]
        Task<PageResult<TPlTruckBackReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckBack/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckBack/GetList")]
        Task<PageResult<TPlTruckBackReadModel>> GetList();
    }
}