//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlBackReturnApi
    {
        [Post("/plan/TPlBackReturn/Create")]
        Task<OperationResult> Create([Body] TPlBackReturnCreateModel createModel);

        [Delete("/plan/TPlBackReturn/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlBackReturn/CheckLocation")]
        Task<OperationResult> CheckLocation(string retLocation = null);

        [Get("/plan/TPlBackReturn/CheckBackLocation")]
        Task<OperationResult> CheckBackLocation(string backLocation = null);

        [Post("/plan/TPlBackReturn/Confirm")]
        Task<OperationResult> Confirm([Body] TPlBackReturnUpdateModel updateModel);

        [Post("/plan/TPlBackReturn/ConfirmC3")]
        Task<OperationResult> ConfirmC3([Body] TPlBackReturnUpdateModel updateModel);

        [Put("/plan/TPlBackReturn/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlBackReturnUpdateModel updateModel);

        [Get("/plan/TPlBackReturn/GetAllBackInfo")]
        Task<PageResult<TPlBackReturnReadModel>> GetAllBackInfo(string bayCode = null);

        [Post("/plan/TPlBackReturn/HoldConfirm")]
        Task<OperationResult> HoldConfirm(string materialNo = null, string retLocation = null, string user = null);

        [Get("/plan/TPlBackReturn/Get/{id}")]
        Task<TPlBackReturnReadModel> Get(string id);

        [Get("/plan/TPlBackReturn/GetPage")]
        Task<PageResult<TPlBackReturnReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlBackReturn/GetPageByString")]
        Task<PageResult<TPlBackReturnReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlBackReturn/GetListByString")]
        Task<PageResult<TPlBackReturnReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlBackReturn/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlBackReturn/GetList")]
        Task<PageResult<TPlBackReturnReadModel>> GetList();
    }
}