//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlProductionDetailApi
    {
        [Post("/plan/TPlProductionDetail/Create")]
        Task<OperationResult> Create([Body] TPlProductionDetailCreateModel createModel);

        [Put("/plan/TPlProductionDetail/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlProductionDetailUpdateModel updateModel);

        [Delete("/plan/TPlProductionDetail/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlProductionDetail/Get/{id}")]
        Task<TPlProductionDetailReadModel> Get(string id);

        [Get("/plan/TPlProductionDetail/GetPage")]
        Task<PageResult<TPlProductionDetailReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlProductionDetail/GetPageByString")]
        Task<PageResult<TPlProductionDetailReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlProductionDetail/GetListByString")]
        Task<PageResult<TPlProductionDetailReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlProductionDetail/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlProductionDetail/GetList")]
        Task<PageResult<TPlProductionDetailReadModel>> GetList();
    }
}