//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlBackRepackApi
    {
        [Post("/plan/TPlBackRepack/Create")]
        Task<OperationResult> Create([Body] TPlBackRepackCreateModel createModel);

        [Put("/plan/TPlBackRepack/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlBackRepackUpdateModel updateModel);

        [Delete("/plan/TPlBackRepack/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlBackRepack/Get/{id}")]
        Task<TPlBackRepackReadModel> Get(string id);

        [Get("/plan/TPlBackRepack/GetPage")]
        Task<PageResult<TPlBackRepackReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlBackRepack/GetPageByString")]
        Task<PageResult<TPlBackRepackReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlBackRepack/GetListByString")]
        Task<PageResult<TPlBackRepackReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlBackRepack/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlBackRepack/GetList")]
        Task<PageResult<TPlBackRepackReadModel>> GetList();
    }
}