//<auto-generated />

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTruckTransferApi
    {
        [Get("/plan/TPlTruckTransfer/GetAllTruckNos_old")]
        Task<PageResult<TPlTruckTransferReadModel>> GetAllTruckNos_old(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckTransfer/GetAllTruckNos")]
        Task<PageResult<TPlTruckTransferReadModel>> GetAllTruckNos(string where = null, string orders = null);

        [Post("/plan/TPlTruckTransfer/CompleTransfer")]
        Task<OperationResult> CompleTransfer([Body] TPlTruckTransferUpdateModel updateModel);

        [Get("/plan/TPlTruckTransfer/GetTruckInfo")]
        Task<PageResult<TPlTruckTransferReadModel>> GetTruckInfo(string truckNo = null);

        [Post("/plan/TPlTruckTransfer/GetAllUnpicked_old")]
        Task<OperationResult<PageResult<VPlMaterialReadModel>>> GetAllUnpicked_old(int? current = null, int? pageSize = null, string transferNo = null, string materialNo = null);

        [Post("/plan/TPlTruckTransfer/GetAllUnpicked")]
        Task<OperationResult<PageResult<VPlMaterialReadModel>>> GetAllUnpicked(int? current = null, int? pageSize = null, string transferNo = null, string materialNo = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckTransfer/GetAllPicked_old")]
        Task<PageResult<VPlMaterialReadModel>> GetAllPicked_old(string transferNo = null);

        [Post("/plan/TPlTruckTransfer/GetAllPicked")]
        Task<PageResult<VPlMaterialReadModel>> GetAllPicked(string transferNo = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckTransfer/Pick")]
        Task<OperationResult> Pick(string transferNo = null, string materialNo = null);

        [Post("/plan/TPlTruckTransfer/Unpick")]
        Task<OperationResult> Unpick(string transferNo = null, string materialNo = null, string[] materialNos = null);

        [Post("/plan/TPlTruckTransfer/Confirm")]
        Task<OperationResult> Confirm(string transferNo = null);

        [Post("/plan/TPlTruckTransfer/Cancel")]
        Task<OperationResult> Cancel(string transferNo = null);

        [Post("/plan/TPlTruckTransfer/DeleteTransfer")]
        Task<OperationResult> DeleteTransfer(string transferNo = null);

        [Get("/plan/TPlTruckTransfer/ImportPickModel")]
        Task ImportPickModel();

        [Multipart]
        [Post("/plan/TPlTruckTransfer/ImportPickData")]
        Task<OperationResult> ImportPickData(MultipartItem file, string transferNo = null);

        [Post("/plan/TPlTruckTransfer/GetPickTypeNum")]
        Task<OperationResult<List<int>>> GetPickTypeNum(string[] bayCodes = null, string transferNo = null);

        [Post("/plan/TPlTruckTransfer/GetPickTypeLineNum")]
        Task<OperationResult<List<int>>> GetPickTypeLineNum(string[] bayCodes = null, string transferNo = null);

        [Post("/plan/TPlTruckTransfer/AutoTransferPickDirect")]
        Task<OperationResult> AutoTransferPickDirect(int?[] pickTypes = null, string[] bayCodes = null, string transferNo = null, int? isDirectTruck = null);

        [Post("/plan/TPlTruckTransfer/Create")]
        Task<OperationResult> Create([Body] TPlTruckTransferCreateModel createModel);

        [Put("/plan/TPlTruckTransfer/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckTransferUpdateModel updateModel);

        [Delete("/plan/TPlTruckTransfer/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTruckTransfer/Get/{id}")]
        Task<TPlTruckTransferReadModel> Get(string id);

        [Get("/plan/TPlTruckTransfer/GetPage")]
        Task<PageResult<TPlTruckTransferReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckTransfer/GetPageByString")]
        Task<PageResult<TPlTruckTransferReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckTransfer/GetListByString")]
        Task<PageResult<TPlTruckTransferReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckTransfer/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckTransfer/GetList")]
        Task<PageResult<TPlTruckTransferReadModel>> GetList();
    }
}