//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlProductionApi
    {
        /// <summary>
        /// 查询计划上料的物料信息
        /// </summary>
        [Post("/plan/TPlProduction/GetPlanDetails")]
        Task<PageResult<TPlProductionDetailReadModel>> GetPlanDetails(string planNo = null);

        [Post("/plan/TPlProduction/Create")]
        Task<OperationResult> Create([Body] TPlProductionCreateModel createModel);

        [Put("/plan/TPlProduction/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlProductionUpdateModel updateModel);

        [Delete("/plan/TPlProduction/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlProduction/Get/{id}")]
        Task<TPlProductionReadModel> Get(string id);

        [Get("/plan/TPlProduction/GetPage")]
        Task<PageResult<TPlProductionReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlProduction/GetPageByString")]
        Task<PageResult<TPlProductionReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlProduction/GetListByString")]
        Task<PageResult<TPlProductionReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlProduction/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlProduction/GetList")]
        Task<PageResult<TPlProductionReadModel>> GetList();
    }
}