//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlMaterialApi
    {
        [Put("/plan/TPlMaterial/UpdateMat/{id}")]
        Task<OperationResult> UpdateMat(string id, [Body] TPlMaterialUpdateModel updateModel);

        [Get("/plan/TPlMaterial/GetListByNo")]
        Task<PageResult<TPlMaterialReadModel>> GetListByNo(string materialNo = null);

        [Get("/plan/TPlMaterial/GetPageByString")]
        Task<PageResult<TPlMaterialReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlMaterial/GetListByDefectType")]
        Task<PageResult<TPlMaterialReadModel>> GetListByDefectType();

        [Get("/plan/TPlMaterial/GetCoilState")]
        Task<TPlMaterialReadModel> GetCoilState(string materialId = null);

        [Get("/plan/TPlMaterial/GetMaterialDefectDesc")]
        Task<int> GetMaterialDefectDesc(string materialId = null);

        [Get("/plan/TPlMaterial/UpdateCoilState")]
        Task<int> UpdateCoilState([Body] TPlMaterialReadModel pl);

        /// <summary>
        /// 更改物料信息
        /// </summary>
        /// <returns></returns>
        [Put("/plan/TPlMaterial/UpdateCoilInfo")]
        Task<OperationResult> UpdateCoilInfo([Body] TPlMaterialUpdateModel updateModel);

        /// <summary>
        /// 获取物料信息
        /// </summary>
        /// <returns></returns>
        [Get("/plan/TPlMaterial/GetMaterialWeight")]
        Task<int> GetMaterialWeight(string materialNo = null);

        [Get("/plan/TPlMaterial/ConfirmOut")]
        Task<bool> ConfirmOut(string bayName = null, string coilNo = null);

        [Get("/plan/TPlMaterial/GetQueryPageList")]
        Task<PageResult<TPlMaterialReadModel>> GetQueryPageList([Query] string[] time = null, int? current = null, int? pageSize = null);

        [Post("/plan/TPlMaterial/Create")]
        Task<OperationResult> Create([Body] TPlMaterialCreateModel createModel);

        [Put("/plan/TPlMaterial/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlMaterialUpdateModel updateModel);

        [Delete("/plan/TPlMaterial/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlMaterial/Get/{id}")]
        Task<TPlMaterialReadModel> Get(string id);

        [Get("/plan/TPlMaterial/GetPage")]
        Task<PageResult<TPlMaterialReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlMaterial/GetListByString")]
        Task<PageResult<TPlMaterialReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlMaterial/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlMaterial/GetList")]
        Task<PageResult<TPlMaterialReadModel>> GetList();
    }
}