//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlDeliveryPlanApi
    {
        /// <summary>
        /// 备料，发货量统计
        /// </summary>
        [Get("/plan/TPlDeliveryPlan/GetMpAnalysis")]
        Task<MpStatModels> GetMpAnalysis(string pHouse = null, string planDate = null);

        /// <summary>
        /// 备料占比订单
        /// </summary>
        [Get("/plan/TPlDeliveryPlan/GetPlanMaterialPercentOrder")]
        Task<List<MpStatModelAllBay>> GetPlanMaterialPercentOrder(string pHouse = null, string planDate = null, string percent = null);

        [Post("/plan/TPlDeliveryPlan/Create")]
        Task<OperationResult> Create([Body] TPlDeliveryPlanCreateModel createModel);

        [Put("/plan/TPlDeliveryPlan/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlDeliveryPlanUpdateModel updateModel);

        [Delete("/plan/TPlDeliveryPlan/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlDeliveryPlan/Get/{id}")]
        Task<TPlDeliveryPlanReadModel> Get(string id);

        [Get("/plan/TPlDeliveryPlan/GetPage")]
        Task<PageResult<TPlDeliveryPlanReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlDeliveryPlan/GetPageByString")]
        Task<PageResult<TPlDeliveryPlanReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlDeliveryPlan/GetListByString")]
        Task<PageResult<TPlDeliveryPlanReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlDeliveryPlan/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlDeliveryPlan/GetList")]
        Task<PageResult<TPlDeliveryPlanReadModel>> GetList();
    }
}