//<auto-generated />

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlBayApi
    {
        [Get("/plan/TPlBay/GetPagePlayAndTaskByString")]
        Task<PageResult<TPlBayReadCraneTaskModel>> GetPagePlayAndTaskByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Post("/plan/TPlBay/CreateBayPlan")]
        Task<OperationResult> CreateBayPlan([Body] TPlBayCreateModel createModel);

        [Post("/plan/TPlBay/CreateBayPlanBatch")]
        Task<OperationResult> CreateBayPlanBatch([Body] TPlBayBatchCreateModel createModel);

        [Get("/plan/TPlBay/GetLibLocation")]
        Task<ValueTuple<List<TTrLocationMaterialReadModel>, int>> GetLibLocation([Body] TPlBayBatchCreateModel createModel);

        [Get("/plan/TPlBay/GetKongLocation")]
        Task<ValueTuple<List<TTrLocationMaterialReadModel>, int>> GetKongLocation([Body] TPlBayBatchCreateModel createModel);

        [Post("/plan/TPlBay/AddFinishLinePlan")]
        Task<OperationResult> AddFinishLinePlan(string materialNo = null);

        [Get("/plan/TPlBay/GetCranePlan")]
        Task<PageResult<TPlBayReadModel>> GetCranePlan(string bayId = null, string type = null, string craneName = null);

        [Post("/plan/TPlBay/HoldCreatePlan")]
        Task<OperationResult> HoldCreatePlan(string material = null, string destLocation = null, string type = null);

        [Put("/plan/TPlBay/UpdatePlanPriority")]
        Task<int> UpdatePlanPriority(string bayId = null, string materialNo = null);

        [Put("/plan/TPlBay/UpdateBayPlan")]
        Task<OperationResult> UpdateBayPlan([Body] TPlBayUpdateModel updateModel);

        [Put("/plan/TPlBay/ResettingTask")]
        Task<OperationResult> ResettingTask(string id = null);

        [Put("/plan/TPlBay/BatchResettingPlan")]
        Task<OperationResult> BatchResettingPlan(string[] ids = null);

        [Delete("/plan/TPlBay/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlBay/PlanIsNotExist")]
        Task<TPlBayReadModel> PlanIsNotExist(string materialNo = null);

        [Post("/plan/TPlBay/Create")]
        Task<OperationResult> Create([Body] TPlBayCreateModel createModel);

        [Put("/plan/TPlBay/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlBayUpdateModel updateModel);

        [Get("/plan/TPlBay/Get/{id}")]
        Task<TPlBayReadModel> Get(string id);

        [Get("/plan/TPlBay/GetPage")]
        Task<PageResult<TPlBayReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlBay/GetPageByString")]
        Task<PageResult<TPlBayReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlBay/GetListByString")]
        Task<PageResult<TPlBayReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlBay/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlBay/GetList")]
        Task<PageResult<TPlBayReadModel>> GetList();
    }
}