//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public interface ITPlTruckDeliveryDetailApi
    {
        [Post("/plan/TPlTruckDeliveryDetail/Create")]
        Task<OperationResult> Create([Body] TPlTruckDeliveryDetailCreateModel createModel);

        [Put("/plan/TPlTruckDeliveryDetail/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckDeliveryDetailUpdateModel updateModel);

        [Delete("/plan/TPlTruckDeliveryDetail/Delete")]
        Task<OperationResult> Delete([Query] string[] ids = null);

        [Get("/plan/TPlTruckDeliveryDetail/Get/{id}")]
        Task<TPlTruckDeliveryDetailReadModel> Get(string id);

        [Get("/plan/TPlTruckDeliveryDetail/GetPage")]
        Task<PageResult<TPlTruckDeliveryDetailReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckDeliveryDetail/GetPageByString")]
        Task<PageResult<TPlTruckDeliveryDetailReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckDeliveryDetail/GetListByString")]
        Task<PageResult<TPlTruckDeliveryDetailReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckDeliveryDetail/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckDeliveryDetail/GetList")]
        Task<PageResult<TPlTruckDeliveryDetailReadModel>> GetList();
    }
}