//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlCrossBayTaskApi
    {
        [Post("/plan/TPlCrossBayTask/Create")]
        Task<OperationResult> Create([Body] TPlCrossBayTaskCreateModel createModel);

        [Put("/plan/TPlCrossBayTask/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlCrossBayTaskUpdateModel updateModel);

        [Delete("/plan/TPlCrossBayTask/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlCrossBayTask/Get/{id}")]
        Task<TPlCrossBayTaskReadModel> Get(string id);

        [Get("/plan/TPlCrossBayTask/GetPage")]
        Task<PageResult<TPlCrossBayTaskReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlCrossBayTask/GetPageByString")]
        Task<PageResult<TPlCrossBayTaskReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlCrossBayTask/GetListByString")]
        Task<PageResult<TPlCrossBayTaskReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlCrossBayTask/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlCrossBayTask/GetList")]
        Task<PageResult<TPlCrossBayTaskReadModel>> GetList();
    }
}