//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTruckLoadListHistoryApi
    {
        [Get("/plan/TPlTruckLoadListHistory/GetAllLoadingNos")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetAllLoadingNos(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckLoadListHistory/GetAllPicked")]
        Task<PageResult<TPlMaterialReadModel>> GetAllPicked(string vehicleNo = null, string truckLoadingNo = null, string detailNo = null, string where = null, string orders = null);

        [Post("/plan/TPlTruckLoadListHistory/Cancel")]
        Task<OperationResult> Cancel(string vehicleNo = null, string mainTruckLoadingNo = null, string sourceHouse = null);

        [Post("/plan/TPlTruckLoadListHistory/Create")]
        Task<OperationResult> Create([Body] TPlTruckLoadListCreateModel createModel);

        [Put("/plan/TPlTruckLoadListHistory/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckLoadListUpdateModel updateModel);

        [Delete("/plan/TPlTruckLoadListHistory/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTruckLoadListHistory/Get/{id}")]
        Task<TPlTruckLoadListReadModel> Get(string id);

        [Get("/plan/TPlTruckLoadListHistory/GetPage")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckLoadListHistory/GetPageByString")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckLoadListHistory/GetListByString")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckLoadListHistory/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckLoadListHistory/GetList")]
        Task<PageResult<TPlTruckLoadListReadModel>> GetList();
    }
}