//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlTruckDeliveryApi
    {
        [Post("/plan/TPlTruckDelivery/Create")]
        Task<OperationResult> Create([Body] TPlTruckDeliveryCreateModel createModel);

        [Put("/plan/TPlTruckDelivery/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlTruckDeliveryUpdateModel updateModel);

        [Delete("/plan/TPlTruckDelivery/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlTruckDelivery/Get/{id}")]
        Task<TPlTruckDeliveryReadModel> Get(string id);

        [Get("/plan/TPlTruckDelivery/GetPage")]
        Task<PageResult<TPlTruckDeliveryReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlTruckDelivery/GetPageByString")]
        Task<PageResult<TPlTruckDeliveryReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlTruckDelivery/GetListByString")]
        Task<PageResult<TPlTruckDeliveryReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlTruckDelivery/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlTruckDelivery/GetList")]
        Task<PageResult<TPlTruckDeliveryReadModel>> GetList();
    }
}