//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface ITPlAutoCodeApi
    {
        [Get("/plan/TPlAutoCode/CreatePlanId")]
        Task<string> CreatePlanId();

        [Get("/plan/TPlAutoCode/CreateTransferNo")]
        Task<string> CreateTransferNo();

        [Post("/plan/TPlAutoCode/Create")]
        Task<OperationResult> Create([Body] TPlAutoCodeCreateModel createModel);

        [Put("/plan/TPlAutoCode/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] TPlAutoCodeUpdateModel updateModel);

        [Delete("/plan/TPlAutoCode/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/TPlAutoCode/Get/{id}")]
        Task<TPlAutoCodeReadModel> Get(string id);

        [Get("/plan/TPlAutoCode/GetPage")]
        Task<PageResult<TPlAutoCodeReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/TPlAutoCode/GetPageByString")]
        Task<PageResult<TPlAutoCodeReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/TPlAutoCode/GetListByString")]
        Task<PageResult<TPlAutoCodeReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/TPlAutoCode/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/TPlAutoCode/GetList")]
        Task<PageResult<TPlAutoCodeReadModel>> GetList();
    }
}