//<auto-generated />

using System.Threading.Tasks;
using Refit;
using WmsApi;
using WmsApi.Contracts.Models;

namespace WmsApi.Plan
{
    public partial interface IVProductionMaterialApi
    {
        [Post("/plan/VProductionMaterial/Create")]
        Task<OperationResult> Create([Body] VProductionMaterialCreateModel createModel);

        [Put("/plan/VProductionMaterial/Update/{id}")]
        Task<OperationResult> Update(string id, [Body] VProductionMaterialUpdateModel updateModel);

        [Delete("/plan/VProductionMaterial/Delete")]
        Task<OperationResult> Delete(string[] ids = null);

        [Get("/plan/VProductionMaterial/Get/{id}")]
        Task<VProductionMaterialReadModel> Get(string id);

        [Get("/plan/VProductionMaterial/GetPage")]
        Task<PageResult<VProductionMaterialReadModel>> GetPage(int? current = null, int? pageSize = null);

        [Get("/plan/VProductionMaterial/GetPageByString")]
        Task<PageResult<VProductionMaterialReadModel>> GetPageByString(int? current = null, int? pageSize = null, string where = null, string orders = null);

        [Get("/plan/VProductionMaterial/GetListByString")]
        Task<PageResult<VProductionMaterialReadModel>> GetListByString(string where = null, string orders = null);

        [Get("/plan/VProductionMaterial/CreateReportExcel")]
        Task CreateReportExcel(string where = null, string orders = null, string reportName = null);

        [Get("/plan/VProductionMaterial/GetList")]
        Task<PageResult<VProductionMaterialReadModel>> GetList();
    }
}